const CATEGORIES = {
  world: ["bbc", "bbc_world", "bbc_uk", "bbc_politics", "bbc_education", "bbc_asia", "bbc_africa", "bbc_europe", "bbc_middleeast", "bbc_latam", "bbc_us", "bbc_entertainment", "bbc_health", "bbc_magazine", "bbc_worklife", "bbc_future", "bbc_travel", "bbc_culture", "bbc_reel", "cnn", "cnn_world", "cnn_us", "cnn_politics", "guardian", "guardian_uk", "guardian_us", "guardian_opinion", "guardian_australia", "guardian_europe", "guardian_global_dev", "guardian_inequality", "guardian_cities", "aljazeera", "npr", "npr_world", "npr_politics", "pbs", "skynews", "skynews_uk", "skynews_politics", "dw", "france24", "nhk", "axios", "thehill", "nytimes", "nytimes_world", "nytimes_us", "nytimes_politics", "nytimes_opinion", "nytimes_magazine", "nytimes_sunday", "nytimes_dealbook", "nytimes_upshot", "foxnews", "abcnews", "cbsnews", "vox", "slate", "newsweek", "huffpost", "time", "theintercept", "thedailybeast", "salon", "motherjones", "reason", "foreignpolicy", "theatlantic", "csmonitor", "propublica", "theconversation", "globalvoices", "dailymail", "mirror_uk", "metro_uk", "thesun", "usatoday_top", "usatoday_world", "rt_news", "xinhua", "tass", "wsj_world", "wsj_opinion", "digg", "ladbible", "unilad", "buzzfeed", "independent", "independent_world", "telegraph_uk", "express_uk", "standard_uk", "ibtimes", "theweek", "vice", "politico_us", "realclearpolitics", "thefederalist", "jacobin", "thenation", "newrepublic", "spectator_uk", "prospect_uk", "unherd", "quillette", "commondreams", "truthout", "rawstory", "thediplomat", "un_news", "wef_agenda", "counterpunch", "currentaffairs", "thecritic", "antiwar", "worldpoliticsreview"],
  asia: ["scmp", "straitstimes", "abcaus", "abcaus_world", "abcaus_tech", "abcaus_science", "abcaus_business", "abcaus_sports", "abcaus_entertainment", "abcaus_health", "cbcca", "cbcca_world", "cbcca_tech", "cbcca_politics", "cbcca_business", "cbcca_sports", "cbc_health", "cbc_entertainment", "cbc_science", "japantimes", "japantimes_business", "japantimes_sports", "japantimes_life", "bangkokpost", "channelnewsasia", "smh", "globalnews_ca", "globalnews_politics", "globalnews_money", "globalnews_tech", "globalnews_health", "globalnews_entertainment", "globalnews_sports", "stuff_nz", "dawn", "dawn_world", "dawn_tech", "dawn_sport", "dawn_business", "dailystar_bd", "inquirer_ph", "nzherald", "bbc_asia", "dw_asia", "tribune_pk", "tribune_pk_tech", "tribune_pk_sports", "geo_tv", "samaa", "koreaherald", "koreatimes", "taiwannews", "rappler_ph", "bangkokpost_biz", "thestar_my", "bernama", "vnexpress", "theaustralian", "watoday", "brisbanetimes", "canberratimes", "torontosun", "montrealgazette", "vancouversun", "ottawacitizen", "calgaryherald", "winnipegfreepress", "techinasia", "e27", "koreajoongangdaily", "asiaone", "todayonline_sg", "dhaka_tribune", "kathmandu_post", "irrawaddy", "phnom_penh_post", "manila_bulletin", "krasia", "nikkeiasia"],
  india: ["ndtv", "ndtv_india", "ndtv_world", "ndtv_sports", "ndtv_tech", "ndtv_business", "ndtv_entertainment", "ndtv_food", "ndtv_auto", "ndtv_profit", "toi", "toi_world", "toi_tech", "toi_sports", "toi_entertainment", "toi_business", "toi_city", "toi_life", "toi_education", "hindustantimes", "hindustantimes_world", "hindustantimes_sports", "hindustantimes_entertainment", "hindustantimes_tech", "hindustantimes_business", "hindustantimes_lifestyle", "hindustantimes_education", "hindustantimes_cricket", "thehindu", "thehindu_international", "thehindu_sports", "thehindu_entertainment", "thehindu_science", "thehindu_tech", "thehindu_business", "thehindu_education", "thehindu_opinion", "frontline_hindu", "indianexpress", "indianexpress_world", "indianexpress_tech", "indianexpress_sports", "indianexpress_entertainment", "indianexpress_lifestyle", "indianexpress_business", "indianexpress_education", "indianexpress_opinion", "economictimes", "economictimes_tech", "economictimes_markets", "economictimes_startups", "livemint", "livemint_tech", "livemint_markets", "livemint_opinion", "livemint_economy", "livemint_lounge", "mint_opinion", "indiatoday", "indiatoday_india", "indiatoday_tech", "businessstandard", "businessstandard_markets", "news18", "news18_world", "news18_tech", "news18_sports", "news18_entertainment", "news18_business", "news18_lifestyle", "news18_education", "dnaindia", "oneindia", "tribuneindia", "swarajya", "scroll_in", "thequint", "outlook_india", "rediff", "wion", "wion_world", "wion_tech", "wion_entertainment", "wion_sports", "zeenews", "zeenews_world", "zeenews_tech", "zeenews_sports", "zeenews_entertainment", "zeenews_health", "abplive", "aajtak", "gadgets360", "carandbike", "moneycontrol_personal", "thewire_in", "firstpost", "deccanherald", "deccanchronicle", "asianage", "newindianexpress", "telanganatoday", "thestatesman", "freepressjournal", "mid_day", "theweek_in", "opindia", "theprintindia", "theprint_opinion", "newslaundry", "caravandaily", "nationalherald", "dailyo", "pgurus", "orfonline", "financialexpress", "financialexpress_market", "financialexpress_tech", "financialexpress_bfsi", "inc42", "entrackr", "vccircle", "medianamaindia", "gadgetsnow", "techpp", "pinkvilla", "bollywoodlife", "filmcompanion", "insidesport"],
  middleeast: ["jerusalempost", "arabnews", "arabnews_sport", "arabnews_tech", "arabnews_lifestyle", "thenationalnews", "middleeasteye", "almonitor", "aljazeera", "bbc_middleeast", "gulfnews", "khaleejtimes", "dailysabah", "haaretz", "timesofisrael", "al_arabiya", "jordantimes", "newturkey", "irna_en", "tehrantimes", "trtworld", "rudaw", "newlinesmagazine"],
  europe: ["lemonde", "derspiegel", "elpais", "euronews", "irish_times", "dutchnews", "thelocal_se", "thelocal_de", "thelocal_fr", "thelocal_it", "thelocal_es", "thelocal_no", "thelocal_at", "thelocal_ch", "thelocal_dk", "thelocal_pl", "rte", "swissinfo", "balkan_insight", "politico_eu", "politico_eu_tech", "bbc_europe", "dw_europe", "guardian_europe", "euractiv", "euobserver", "scotsman", "walesonline", "kyivindependent", "bne_intellinews", "thenordics", "thelocal_fi", "portugal_news", "romania_insider", "praguemorning", "budapesttimes", "icelandreview", "greekcitytimes", "baltic_times", "croatiaweek", "theneweuropean", "europeansting", "connexionfrance", "theolivepress", "cyprus_mail", "sofia_globe", "thejournal_ie", "belfasttelegraph", "heraldscotland", "cityam"],
  latam: ["mercopress", "batimes", "ticotimes", "brasilwire", "bbc_latam", "thecitypaperbogota", "dialogo_americas", "mexiconewsdaily", "riotimesonline", "colombiareports", "peruthisweek", "argentinaindependent", "santiagotimes", "caribbeannewsglobal", "jamaicagleaner", "trinidadexpress", "havana_times", "insightcrime", "globalamericans", "nearshoreamericas", "latamlist", "contxto"],
  africa: ["allafrica", "news24_sa", "theeastafrican", "citizen_za", "punch_ng", "premiumtimes_ng", "nation_ke", "bbc_africa", "theafricareport", "iol_za", "businesslive_za", "mg_za", "vanguard_ng", "thecable_ng", "monitor_ug", "daily_maverick", "sahara_reporters", "standard_ke", "newvision_ug", "herald_zw", "times_zm", "observer_ug", "ethiopianreporter", "africanews", "groundup_za", "theconversation_africa", "africanarguments", "enca", "nairametrics", "techcabal", "technext", "techpoint_africa", "disruptafrica", "weetracker"],
  business: ["bloomberg", "cnbc", "cnbc_world", "cnbc_tech", "cnbc_finance", "cnbc_earnings", "cnbc_personal_finance", "marketwatch", "marketwatch_markets", "marketwatch_personal", "businessinsider", "ft", "moneycontrol", "moneycontrol_markets", "moneycontrol_business", "moneycontrol_tech", "seeking_alpha", "yahoo_finance", "nytimes_business", "nytimes_economy", "nytimes_dealbook", "guardian_business", "guardian_money", "investing_com", "fortune", "fortune_tech", "fortune_leadership", "fastcompany", "entrepreneur", "inc", "hbr", "skynews_business", "dw_business", "npr_business", "npr_planet_money", "economictimes", "economictimes_markets", "businessstandard", "businessstandard_markets", "livemint", "livemint_markets", "quartz", "theeconomist", "wharton_blog", "mckinsey", "bain", "thestreet", "benzinga", "kiplinger", "barrons", "wsjmarkets", "wsj_tech", "wsj_lifestyle", "wsj_economy", "cnn_money", "morningstar", "zacks", "fool_uk", "proactiveinvestors", "nasdaq_news", "afr_au", "project_syndicate", "nakedcapitalism", "wolfstreet", "marketbeat", "stockanalysis", "thisismoney", "cityam", "stratechery", "ben_evans"],
  crypto: ["coindesk", "cointelegraph", "theblock", "decrypt", "bitcoinmagazine", "cryptoslate", "beincrypto", "ambcrypto", "cryptopotato", "defiant", "blockonomi", "newsbtc", "dailyhodl", "unchained", "bankless", "u_today", "coingecko_buzz", "bitcoinist", "zycrypto", "cryptobriefing", "coinspeaker", "cryptonews", "nulltx", "coinjournal", "crypto_news_flash", "thecryptobasic", "coinpedia", "defi_pulse", "rekt_news", "chainalysis_blog", "etherscan_blog", "web3_is_going_great", "nftevening", "metaversepost", "web3daily", "glassnode_insights", "dappradar_blog", "nansen_blog", "messari_newsletter"],
  technology: ["bbc_tech", "cnn_tech", "guardian_tech", "nytimes_tech", "techcrunch", "techcrunch_apps", "techcrunch_gadgets", "theverge", "wired", "wired_gear", "arstechnica", "arstechnica_gadgets", "engadget", "hackernews", "hackernews_best", "hackernews_show", "hackernews_ask", "mashable", "zdnet", "zdnet_ai", "zdnet_developer", "zdnet_cloud", "zdnet_networking", "tomshardware", "androidcentral", "androidauthority", "nine_to_five_mac", "nine_to_five_google", "thenextweb", "gizmodo", "cnet", "techradar", "theregister", "slashdot", "pcworld", "macrumors", "mit_tech_review", "howtogeek", "xda", "windowscentral", "bleepingcomputer", "digitaltrends", "lifehacker", "makeuseof", "appleinsider", "phonearena", "gsmarena", "notebookcheck", "anandtech", "protocoldotcom", "restofworld", "skynews_tech", "venturebeat", "tnw_latest", "bgr", "geekwire", "torrentfreak", "boingboing", "hackday", "spectrum_ieee", "ifixit", "omgubuntu", "fossforce", "itsfoss", "phoronix", "liliputing", "techmeme", "techspot", "neowin", "betanews", "techpowerup", "talkandroid", "imore", "nine_to_five_toys", "pocket_lint", "trusted_reviews", "t3", "stuff_tv", "lifewire", "tomsguide", "laptopmag", "pcmag", "informationweek", "computerweekly", "itpro", "techrepublic", "silicon_uk", "readwrite", "technode", "androidpolice", "chromeunboxed", "wccftech", "tweaktown", "overclock3d", "guru3d", "hexus", "independent_tech", "ibtimes_tech", "siliconangle", "computerworld", "cio_com", "networkworld", "lobsters", "servethehome", "storagereview", "sdtimes", "phandroid", "gadgethacks", "techviral", "interestingengineering", "apple_newsroom", "samsung_newsroom", "intel_newsroom", "qualcomm_blog"],
  cybersecurity: ["darkreading", "threatpost", "krebsonsecurity", "securityweek", "thehackernews_sec", "naked_security", "hackernews_security", "schneier", "cyberscoop", "zdnet_security", "tripwire", "bleepingcomputer", "wired_security", "infosecurity_mag", "csoonline", "scmagazine", "hackread", "gbhackers", "securityboulevard", "portswigger", "securityintelligence", "cybersecuritynews", "malwarebytes_blog", "sentinelone_blog", "threcord", "we_live_security", "venturebeat_security", "snyk_blog", "aquasec_blog", "sysdig_blog", "talosintelligence"],
  programming: ["dev_to", "dev_to_top", "dev_to_devops", "dev_to_react", "dev_to_python", "dev_to_javascript", "dev_to_webdev", "dev_to_career", "dev_to_tutorial", "dev_to_opensource", "dev_to_ai", "dev_to_cloud", "dev_to_database", "dev_to_security", "dev_to_rust", "dev_to_go", "dev_to_node", "hackernoon", "smashingmag", "css_tricks", "sitepoint", "infoq", "dzone", "github_blog", "github_changelog", "github_engineering", "freecodecamp", "stackoverflow_blog", "devops_com", "thenewstack", "hashnode", "medium_programming", "logrocket", "medium_javascript", "medium_python", "medium_webdev", "medium_devops", "medium_react", "realpython", "theserverside", "codeproject", "phparch", "rubyweekly", "kotlinblog", "rustblog", "goblog", "medium_nodejs", "medium_typescript", "medium_flutter", "medium_android", "medium_ios", "medium_docker", "medium_kubernetes", "medium_aws", "medium_blockchain", "medium_datascience", "flutter_dev", "docker_blog", "kubernetes_blog", "aws_blog", "azure_blog", "gcp_blog", "vercel_blog", "netlify_blog", "nextjs_blog", "svelte_blog", "vuejs_blog", "react_blog", "angular_blog", "baeldung", "geeksforgeeks", "javacodegeeks", "auth0_blog", "twilio_blog", "stripe_blog", "supabase_blog", "prisma_blog", "planetscale_blog", "hashicorp_blog", "pulumi_blog", "grafana_blog", "datadog_blog", "circleci_blog", "gitlab_blog", "jetbrains_blog", "mozilla_hacks", "webkit_blog", "chromium_blog", "cloudflare_blog", "digitalocean_blog", "linode_blog", "heroku_blog", "fly_io_blog", "render_blog", "opensource_com", "linuxfoundation", "cncf_blog", "css_weekly", "javascript_weekly", "golang_weekly", "react_status", "node_weekly", "frontendfoc_us", "dotnet_blog", "swift_blog", "laravel_news", "spring_blog", "redhat_blog", "ibm_developer", "mongodb_blog", "elastic_blog", "confluent_blog", "cockroachdb_blog", "shopify_engineering", "netflix_tech", "airbnb_engineering", "spotify_engineering", "linkedin_engineering", "meta_engineering", "dropbox_tech", "slack_engineering", "pinterest_engineering", "twitter_engineering", "figma_blog", "notion_blog", "linear_blog", "deno_blog", "bun_blog", "astro_blog", "remix_blog", "tailwindcss_blog", "turborepo_blog", "web_dev", "overreacted", "joshwcomeau", "kentcdodds", "css_irl"],
  ai: ["openai_blog", "deepmind_blog", "mlnews", "towardsdatascience", "analyticsvidhya", "kdnuggets", "venturebeat_ai", "huggingface_blog", "huggingface_papers", "aitrends", "marktechpost", "aibusiness", "aimag", "unite_ai", "datasciencecentral", "medium_ai", "theaijournal", "synced_ai", "thegradient", "importai", "paperswithcode", "nvidia_blog", "google_ai_blog", "microsoft_ai", "meta_ai", "anthropic_news", "distill", "twomin_papers", "aisupremacy", "singularityhub", "stability_ai", "cohere_blog", "mistral_blog", "tensorflowblog", "pytorchblog", "kaggle_blog", "datasciencedojo", "machinelearningplus", "ai_googleblog", "deeplearning_ai", "assemblyai_blog", "pinecone_blog", "replicate_blog", "wandb_blog", "ai_news_io", "bair_blog", "explosion_ai", "langchain_blog", "llamaindex_blog", "simonwillison", "oneusefulthing", "aisnakeoil", "emergentmind", "analytics_india_mag", "datanami", "insidebigdata"],
  science: ["bbc_science", "nytimes_science", "guardian_science", "guardian_space", "npr_science", "sciencedaily", "sciencedaily_health", "sciencedaily_tech", "sciencedaily_environment", "sciencedaily_mind", "nasa", "nasa_image", "newscientist", "newscientist_space", "newscientist_health", "newscientist_tech", "newscientist_env", "phys_org", "phys_org_tech", "phys_org_space", "phys_org_earth", "phys_org_biology", "phys_org_physics", "phys_org_nanotech", "space_com", "livescience", "iflscience", "sciencealert", "smithsonianmag", "popularmechanics", "popsci", "eos", "quantamagazine", "scienceamerican", "wired_science", "arstechnica_science", "thehindu_science", "dw_science", "cosmosmagazine", "cosmos_earth", "cosmos_life", "atlasobscura", "discovermagazine", "technologynetworks", "futurism", "nature_news", "science_mag", "cell_press", "newatlas", "labmanager", "sciencenews", "theconversation_sci", "theconversation_env", "eurekalert", "sciencefocus", "mentalfloss", "physicsworld", "chemistryworld", "biologynews", "earth_com", "archaeology_org", "psychcentral", "scitechdaily", "plosone", "undark", "hakaimagazine", "earthsky", "astronomy_com"],
  space: ["nasa", "nasa_image", "spacenews", "nasaspaceflight", "universetoday", "skyandtelescope", "planetary_org", "spacepolicyonline", "spaceflightnow", "space_com", "phys_org_space", "guardian_space", "esa_news", "arianespace", "astronomynow", "skyatnightmag"],
  health: ["cnn_health", "nytimes_health", "nytimes_wellblog", "npr_health", "shots_npr", "bbc_health", "who_news", "statnews", "medpagetoday", "healthline", "medicalnewstoday", "webmd_news", "everydayhealth", "health_harvard", "psychologytoday", "medscape", "sciencedaily_health", "guardian_health", "fiercepharma", "healio", "nih_news", "cdc_news", "healtheuropa", "fiercehealthcare", "healthaffairs", "zeenews_health", "mayoclinic_news", "clevelandclinic_blog", "hopkinsmedicine", "kaiserhealthnews", "medcitynews", "biopharmadive", "endpts_news", "healthcaredive", "modernhealthcare", "beckers_health", "verywellmind", "verywellhealth", "health_com", "prevention", "goodrx_health", "theconversation_health"],
  climate: ["guardian_environment", "guardian_climate", "guardian_animals", "nytimes_climate", "mongabay", "mongabay_oceans", "mongabay_forests", "carbonbrief", "climatehome", "treehugger", "insideclimatenews", "ecowatch", "grist", "cleantech", "reneweconomy", "sciencedaily_environment", "desmog", "earthorg", "ensia", "yaleclimateconnections", "greenmatters", "circularonline", "energymonitor", "dw_environment", "resilience_org", "greenbiz", "sustainablebrands", "environmentalleader", "cleanenergywire", "solarpowerworldonline", "triplepundit", "esgtoday", "climateaction", "carbontracker", "e360_yale", "nexusmedia", "oceanea_blog"],
  sports: ["bbc_sport", "bbc_football", "bbc_cricket", "bbc_tennis", "bbc_f1", "bbc_rugby", "bbc_golf", "bbc_boxing", "nytimes_sports", "espn", "espn_football", "espn_nba", "espn_nfl", "espn_mlb", "espn_tennis", "espn_f1", "espn_golf", "espn_mma", "espn_rugby", "espn_boxing", "espn_cricket", "skysports", "skysports_football", "skysports_cricket", "skysports_f1", "skysports_nfl", "skysports_golf", "skysports_boxing", "sportskeeda", "cricinfo", "cricbuzz", "f1", "cbssports", "cbssports_nfl", "cbssports_nba", "cbssports_mlb", "theathletic", "sbnation", "sportingnews", "sportingnews_uk", "bleacherreport", "wrestlinginc", "mmafighting", "marca_en", "si_soccer", "talksport", "sportbible", "olympic_news", "ufc", "pga", "nba_news", "mlb_news", "nhl", "football365", "fourfourtwo", "givemesport", "ndtv_sports", "toi_sports", "hindustantimes_sports", "hindustantimes_cricket", "thehindu_sports", "indianexpress_sports", "news18_sports", "guardian_football", "guardian_cricket", "guardian_tennis", "guardian_rugby", "guardian_golf", "guardian_boxing", "guardian_f1", "dw_sports", "zeenews_sports", "wion_sports", "goal_com", "sportstar_hindu", "insidethegames", "cyclingnews", "rugbypass", "swimswam", "tennishead", "independent_sport", "deadspin", "worldsoccer", "motorsport_com", "firstsportz"],
  entertainment: ["variety", "hollywoodreporter", "deadline", "tmz", "eonline", "collider", "screenrant", "avclub", "indiewire", "comicbook", "denofgeek", "slashfilm", "cinemablend", "cbr", "giantfreakinrobot", "theplaylist", "filmschoolrejects", "cnn_entertainment", "bbc_entertainment", "nytimes_arts", "nytimes_movies", "nytimes_theater", "guardian_film", "guardian_tv", "toi_entertainment", "hindustantimes_entertainment", "indianexpress_entertainment", "news18_entertainment", "thehindu_entertainment", "tvline", "tvinsider", "paste_tv", "whatsonnetflix", "decider", "gamesradar_movies", "empireonline", "joblo", "vulture", "pajiba", "bloody_disgusting", "thewrap", "movieweb", "wegotthiscovered", "liveforlivemusic", "anime_news", "crunchyroll_news", "wion_entertainment", "zeenews_entertainment", "skynews_entertainment", "rottentomatoes", "filmthreat", "nofilmschool", "hollywoodlife", "justjared", "popculture", "peoplemagazine", "ew", "syfy_wire", "tor_com", "digitalspy", "nerdist", "geektyrant", "flickeringmyth", "thecinemaholic", "popmatters", "desimartini", "cinema_express", "screencrush"],
  gaming: ["polygon", "ign", "ign_playstation", "ign_xbox", "ign_nintendo", "ign_pc", "kotaku", "eurogamer", "gamespot", "pcgamer", "rockpapershotgun", "nintendolife", "gamesradar", "pushsquare", "purexbox", "destructoid", "gamedeveloper", "dualshockers", "vg247", "siliconera", "toucharcade", "rpgsite", "gameinformer", "hardcore_gamer", "escapist", "mp1st", "playstationblog", "xbox_news", "nindies", "arstechnica_gaming", "gamingbolt", "twinfinite", "thegamer", "gamerant", "segmentnext", "gamepur", "shacknews", "gamesbeat", "pcinvasion", "dotesports", "esportsinsider", "gamesindustry", "steampowered_blog", "videogameschronicle", "massivelyop", "mmobomb", "screenrant_gaming", "cbr_gaming", "indiedb"],
  music: ["billboard", "rollingstone", "rollingstone_music", "pitchfork", "nme", "stereogum", "consequenceofsound", "brooklynvegan", "spin", "loudwire", "metal_injection", "edm_com", "guardian_music", "clash_music", "paste_music", "diymagazine", "tinymixtapes", "fact_mag", "npr_music", "exclaim_music", "udiscovermusic", "thefader", "dancingastronaut", "djmag", "youredm", "americansongwriter", "classicfm", "jazziz", "earmilk"],
  food: ["eater", "eater_national", "bonappetit", "seriouseats", "foodandwine", "tastingtable", "thespruceeats", "epicurious", "saveur", "food52", "nytimes_food", "nytimes_dining", "guardian_food", "guardian_food2", "thekitchn", "thekitchn2", "cookinglight", "delish", "npr_food", "ndtv_food", "foodnavigator", "grubstreet", "finedininglovers", "spoonuniversity", "thetakeout", "punchdrink", "vinepair", "tastecooking"],
  travel: ["cnn_travel", "cnn_travel2", "lonelyplanet", "cntraveler", "travelandleisure", "afar", "matadornetwork", "thepointsguy", "nomadicmatt", "skyscanner_news", "nytimes_travel", "nytimes_travel2", "guardian_travel", "guardian_travel2", "bbc_travel", "fodors", "tourismreview", "breakingtravelnews", "usatoday_travel", "travelweekly", "wanderlust", "roughguides", "travelawaits", "skift", "phocuswire", "timeout", "theculturetrip", "worldnomads"],
  automotive: ["motortrend", "caranddriver", "jalopnik", "autoblog", "topgear", "electrek", "insideevs", "thedrive", "roadandtrack", "carscoops", "carbuzz", "greencarreports", "nytimes_automobiles", "arstechnica_cars", "motor1", "autocar", "autoexpress", "drivetribe", "motorauthority", "carthrottle", "ndtv_auto", "carandbike", "motoringresearch", "carmagazine", "automotiveworld", "hemmings", "bringatrailer"],
  realestate: ["curbed", "housingwire", "inman", "realtor_com", "nytimes_realestate", "bisnow", "propertywire", "globest", "worldpropertyjournal", "mansionsglobal", "therealdeal", "propmodo", "commercial_observer"],
  education: ["mit_news", "ed_week", "insidehighered", "edsurge", "ted_blog", "edutopia", "campustechnology", "timeshighered", "harvard_gazette", "stanford_news", "oxford_news", "cambridge_news", "bbc_education", "npr_education", "guardian_education", "nytimes_education", "wired_education", "khanacademy_blog", "chronicle_he2", "eschoolnews", "teachthought", "edtechmagazine", "hindustantimes_education", "thehindu_education", "indianexpress_education", "news18_education", "toi_education", "universityworldnews", "classcentral", "coursera_blog", "educationnext", "hechingerreport", "wonkhe"],
  law: ["lawfaremedia", "scotusblog", "jurist", "law_com", "techdirt", "eff", "arstechnica_policy", "abovethelaw", "legalcheek", "natlawreview", "lexology", "ipwatchdog", "cdt_org", "accessnow"],
  startups: ["techcrunch_startups", "techcrunch_venture", "saastr", "producthunt", "betalist", "startupgrind", "ycombinator_blog", "crunchbase_news", "eu_startups", "yourstory", "yourstory_social", "economictimes_startups", "seedtable", "techfundingnews", "startupnation", "sifted", "tech_eu", "disruptafrica", "silicon_canals", "jumpstartmag", "inc42", "entrackr", "vccircle"],
  design: ["uxdesign", "abduzeedo", "creativebloq", "yankodesign", "designboom", "archdaily", "dezeen", "core77", "designmilk", "itsnicethat", "designweek", "wallpaper", "inhabitat", "fastcodesign", "colossal", "booooooom", "aiga_eye", "heydesigner", "webdesignerdepot", "speckyboy", "awwwards_blog", "dribbble_blog", "designernews", "mymodernmet", "architecturaldigest"],
  defense: ["defensenews", "warisboring", "defenseone", "breakingdefense", "militarytimes", "warzone", "armscontrol", "navalnews", "airforcemag", "warontherocks", "janes", "cfr_org", "brookings", "rand_org", "chathamhouse", "carnegieendowment", "sipri"],
  philosophy: ["aeon", "brainpickings", "brainpickings2", "openculture", "dailystoic", "philosophynow", "lithub", "electricliterature", "theparisreview", "nytimes_books", "nytimes_bookrev", "npr_books", "guardian_books", "plato_stanford", "psyche_aeon", "farnam_street", "npr_culture", "threequarksdaily", "aldaily", "theschooloflife", "bigthink", "publicdomainreview"],
  personalfinance: ["nerdwallet", "bankrate", "fool", "thebalance", "moneyunder30", "guardian_money", "wise_bread", "thebalance_invest", "thebalance_retirement", "daveramsey", "mrmoneymustache", "financialsamurai", "investopedia_news", "moneycontrol_personal", "usatoday_money", "globalnews_money", "marketwatch_personal", "pennyhoarder", "financialdiet", "dollarsprout"],
  fashion: ["vogue", "gq", "harpersbazaar", "allure", "refinery29", "highsnobiety", "hypebeast", "complex", "nytimes_fashion", "nytimes_style", "guardian_fashion", "wwd", "fashionista", "manrepeller", "beautyindependent", "byrdie", "whowhatwear", "cosmo", "elle", "instyle", "coveteur", "glossy", "businessoffashion", "teenvoguefashion", "marieclaire", "glamour"],
  parenting: ["parents", "todaysparent", "fatherly", "romper", "scarymommy", "whattoexpect", "mother_ly", "familyeducation", "verywellfamily", "parentmap"],
  fitness: ["menshealth", "womenshealth", "runnersworld", "mindbodygreen", "wellandgood", "self_magazine", "yogajournal", "outsideonline", "barbend", "verywellfit", "breakingmuscle", "greatist", "coachmag"],
  home: ["apartmenttherapy", "bobvila", "thekitchn", "bhg", "dwell", "curbed_design", "thisoldhouse", "familyhandyman", "instructables", "remodelista", "gardenista", "thespruce"],
  pets: ["thedodo", "dogster", "catster", "guardian_animals", "akc_news", "petmd", "worldwildlife", "birdwatchingdaily", "horseandhound"],
  photography: ["petapixel", "dpreview", "fstoppers", "diyphotography", "digitalcameraworld", "photofocus", "shutterbug", "thephoblographer", "photographylife"],
  history: ["historydaily", "historyextra", "warhistoryonline", "nytimes_obituaries", "atlasobscura", "historytoday", "worldhistory_org", "militaryhistory", "ancientorigins", "livehistoryindia"],
  lifestyle: ["bustle", "thecut", "manofmany", "coolhunting", "uncrate", "gearpatrol", "thrillist", "popsugar", "thegoodtrade", "minimalismlife", "theeverygirl", "cup_of_jo", "upworthy", "brightly", "guardian_lifestyle", "indianexpress_lifestyle", "hindustantimes_lifestyle", "news18_lifestyle", "toi_life", "wsj_lifestyle", "usatoday_life", "npr_race", "nylon", "dazeddigital", "papermag", "boredpanda", "listverse", "independent_life", "messynessychic", "odditycentral", "twisted_sifter", "goodhousekeeping", "realsimple", "oprah_daily"],
  media: ["nieman_lab", "poynter", "cjr", "mediaite", "pressgazette", "journalism_co_uk", "mediapost", "adweek", "digiday", "adage", "campaignlive", "thedrum", "marketing_week", "podnews"],
  robotics: ["roboticsandautomation", "iotworldtoday", "embedded_com", "eetimes", "staceyoniot"],
  energy: ["oilprice", "energycentral", "utilitydive", "pv_magazine", "windpowermonthly", "rechargenews", "hydrogenfuelnews"],
  biotech: ["fiercebiotech", "genengnews", "biospace", "labiotech", "statnews_pharma"],
  marketing: ["searchengineland", "searchenginejournal", "moz_blog", "contentmarketinginst", "socialmediaexaminer", "neilpatel_blog", "hubspot_blog", "copyblogger"],
  fintech: ["finextra", "fintechfutures", "pymnts", "tearsheet", "bankingdive"],
  semiconductors: ["semiengineering", "eetimes_asia", "semiaccurate"],
  supplychain: ["supplychaindive", "freightwaves", "theloadstar"],
};

function getCategoryForSource(sourceKey) {
  for (const [cat, keys] of Object.entries(CATEGORIES)) {
    if (keys.includes(sourceKey)) return cat;
  }
  return "uncategorized";
}

function getSourcesForCategory(category) {
  return CATEGORIES[category] || [];
}

function listCategories() {
  return Object.entries(CATEGORIES).map(([name, keys]) => ({
    name,
    count: keys.length,
  }));
}

module.exports = { CATEGORIES, getCategoryForSource, getSourcesForCategory, listCategories };
