const CATEGORIES = {
  world: ["bbc", "bbc_world", "bbc_uk", "bbc_politics", "bbc_education", "bbc_asia", "bbc_africa", "bbc_europe", "bbc_middleeast", "bbc_latam", "bbc_us", "bbc_entertainment", "bbc_health", "bbc_magazine", "cnn", "cnn_world", "cnn_us", "cnn_politics", "guardian", "guardian_uk", "guardian_us", "guardian_opinion", "guardian_australia", "guardian_europe", "aljazeera", "npr", "npr_world", "npr_politics", "pbs", "skynews", "skynews_uk", "skynews_politics", "dw", "france24", "nhk", "axios", "thehill", "nytimes", "nytimes_world", "nytimes_us", "nytimes_politics", "nytimes_opinion", "nytimes_magazine", "nytimes_sunday", "foxnews", "abcnews", "cbsnews", "vox", "slate", "newsweek", "huffpost", "time", "theintercept", "thedailybeast", "salon", "motherjones", "reason", "foreignpolicy", "theatlantic", "csmonitor", "propublica", "theconversation", "globalvoices", "dailymail", "mirror_uk", "metro_uk", "thesun", "usatoday_top", "usatoday_world", "rt_news", "xinhua", "tass", "wsj_world", "wsj_opinion", "digg", "ladbible", "unilad", "buzzfeed"],
  asia: ["scmp", "straitstimes", "abcaus", "abcaus_world", "abcaus_tech", "abcaus_science", "abcaus_business", "abcaus_sports", "abcaus_entertainment", "abcaus_health", "cbcca", "cbcca_world", "cbcca_tech", "cbcca_politics", "cbcca_business", "cbcca_sports", "cbc_health", "cbc_entertainment", "cbc_science", "japantimes", "japantimes_business", "japantimes_sports", "japantimes_life", "bangkokpost", "channelnewsasia", "smh", "globalnews_ca", "globalnews_politics", "globalnews_money", "globalnews_tech", "globalnews_health", "globalnews_entertainment", "globalnews_sports", "stuff_nz", "dawn", "dawn_world", "dawn_tech", "dawn_sport", "dawn_business", "dailystar_bd", "inquirer_ph", "nzherald", "bbc_asia", "dw_asia", "tribune_pk", "tribune_pk_tech", "tribune_pk_sports", "geo_tv", "samaa"],
  india: ["ndtv", "ndtv_india", "ndtv_world", "ndtv_sports", "ndtv_tech", "ndtv_business", "ndtv_entertainment", "ndtv_food", "ndtv_auto", "toi", "toi_world", "toi_tech", "toi_sports", "toi_entertainment", "toi_business", "toi_city", "toi_life", "toi_education", "hindustantimes", "hindustantimes_world", "hindustantimes_sports", "hindustantimes_entertainment", "hindustantimes_tech", "hindustantimes_business", "hindustantimes_lifestyle", "hindustantimes_education", "thehindu", "thehindu_international", "thehindu_sports", "thehindu_entertainment", "thehindu_science", "thehindu_tech", "thehindu_business", "thehindu_education", "thehindu_opinion", "indianexpress", "indianexpress_world", "indianexpress_tech", "indianexpress_sports", "indianexpress_entertainment", "indianexpress_lifestyle", "indianexpress_business", "indianexpress_education", "indianexpress_opinion", "economictimes", "economictimes_tech", "economictimes_markets", "economictimes_startups", "livemint", "livemint_tech", "livemint_markets", "mint_opinion", "indiatoday", "indiatoday_india", "indiatoday_tech", "businessstandard", "businessstandard_markets", "news18", "news18_world", "news18_tech", "news18_sports", "news18_entertainment", "news18_business", "news18_lifestyle", "news18_education", "dnaindia", "oneindia", "tribuneindia", "swarajya", "scroll_in", "thequint", "outlook_india", "rediff", "wion", "wion_world", "wion_tech", "wion_entertainment", "wion_sports", "zeenews", "zeenews_world", "zeenews_tech", "zeenews_sports", "zeenews_entertainment", "zeenews_health", "abplive", "aajtak", "gadgets360", "carandbike", "moneycontrol_personal"],
  middleeast: ["jerusalempost", "arabnews", "arabnews_sport", "arabnews_tech", "arabnews_lifestyle", "thenationalnews", "middleeasteye", "almonitor", "aljazeera", "bbc_middleeast"],
  europe: ["lemonde", "derspiegel", "elpais", "euronews", "irish_times", "dutchnews", "thelocal_se", "thelocal_de", "thelocal_fr", "thelocal_it", "thelocal_es", "thelocal_no", "thelocal_at", "thelocal_ch", "thelocal_dk", "thelocal_pl", "rte", "swissinfo", "balkan_insight", "politico_eu", "politico_eu_tech", "bbc_europe", "dw_europe", "guardian_europe", "euractiv", "euobserver", "scotsman", "walesonline", "kyivindependent", "bne_intellinews", "thenordics"],
  latam: ["mercopress", "batimes", "ticotimes", "brasilwire", "bbc_latam", "thecitypaperbogota", "dialogo_americas", "mexiconewsdaily"],
  africa: ["allafrica", "news24_sa", "theeastafrican", "citizen_za", "punch_ng", "premiumtimes_ng", "nation_ke", "bbc_africa", "theafricareport", "iol_za", "businesslive_za", "mg_za", "vanguard_ng", "thecable_ng", "monitor_ug"],
  business: ["bloomberg", "cnbc", "cnbc_world", "cnbc_tech", "cnbc_finance", "cnbc_earnings", "marketwatch", "marketwatch_markets", "businessinsider", "ft", "moneycontrol", "moneycontrol_markets", "moneycontrol_business", "moneycontrol_tech", "seeking_alpha", "yahoo_finance", "nytimes_business", "nytimes_economy", "guardian_business", "guardian_money", "investing_com", "fortune", "fastcompany", "entrepreneur", "inc", "hbr", "skynews_business", "dw_business", "npr_business", "economictimes", "economictimes_markets", "businessstandard", "businessstandard_markets", "livemint", "livemint_markets", "quartz", "theeconomist", "wharton_blog", "mckinsey", "bain", "thestreet", "benzinga", "kiplinger", "barrons", "wsjmarkets", "wsj_tech", "wsj_lifestyle", "cnn_money"],
  crypto: ["coindesk", "cointelegraph", "theblock", "decrypt", "bitcoinmagazine", "cryptoslate", "beincrypto", "ambcrypto", "cryptopotato", "defiant", "blockonomi", "newsbtc", "dailyhodl", "unchained", "bankless", "u_today", "coingecko_buzz", "bitcoinist", "zycrypto", "cryptobriefing", "coinspeaker", "cryptonews", "nulltx", "coinjournal", "crypto_news_flash", "thecryptobasic", "coinpedia"],
  technology: ["bbc_tech", "cnn_tech", "guardian_tech", "nytimes_tech", "techcrunch", "techcrunch_apps", "techcrunch_gadgets", "theverge", "wired", "wired_gear", "arstechnica", "arstechnica_gadgets", "engadget", "hackernews", "hackernews_best", "mashable", "zdnet", "tomshardware", "androidcentral", "androidauthority", "nine_to_five_mac", "nine_to_five_google", "thenextweb", "gizmodo", "cnet", "techradar", "theregister", "slashdot", "pcworld", "macrumors", "mit_tech_review", "howtogeek", "xda", "windowscentral", "bleepingcomputer", "digitaltrends", "lifehacker", "makeuseof", "appleinsider", "phonearena", "gsmarena", "notebookcheck", "anandtech", "protocoldotcom", "restofworld", "skynews_tech", "venturebeat", "tnw_latest", "bgr", "geekwire", "torrentfreak", "boingboing", "hackday", "spectrum_ieee", "ifixit", "omgubuntu", "fossforce", "itsfoss", "phoronix", "liliputing", "techmeme", "techspot", "neowin", "betanews", "techpowerup", "talkandroid", "imore", "nine_to_five_toys", "pocket_lint", "trusted_reviews", "t3", "stuff_tv", "lifewire"],
  cybersecurity: ["darkreading", "threatpost", "krebsonsecurity", "securityweek", "thehackernews_sec", "naked_security", "hackernews_security", "schneier", "cyberscoop", "zdnet_security", "tripwire", "bleepingcomputer", "wired_security", "infosecurity_mag", "csoonline", "scmagazine", "hackread", "gbhackers", "securityboulevard"],
  programming: ["dev_to", "dev_to_top", "hackernoon", "smashingmag", "css_tricks", "sitepoint", "infoq", "dzone", "github_blog", "github_changelog", "freecodecamp", "stackoverflow_blog", "devops_com", "thenewstack", "hashnode", "medium_programming", "logrocket", "medium_javascript", "medium_python", "medium_webdev", "medium_devops", "medium_react", "realpython", "theserverside", "codeproject", "phparch", "rubyweekly", "kotlinblog", "rustblog", "goblog", "medium_nodejs", "medium_typescript", "medium_flutter", "medium_android", "medium_ios", "medium_docker", "medium_kubernetes", "medium_aws", "medium_blockchain", "medium_datascience", "flutter_dev", "docker_blog", "kubernetes_blog", "aws_blog", "azure_blog", "gcp_blog", "vercel_blog", "netlify_blog", "nextjs_blog", "svelte_blog", "vuejs_blog", "react_blog", "angular_blog"],
  ai: ["openai_blog", "deepmind_blog", "mlnews", "towardsdatascience", "analyticsvidhya", "kdnuggets", "venturebeat_ai", "huggingface_blog", "aitrends", "marktechpost", "aibusiness", "aimag", "unite_ai", "datasciencecentral", "medium_ai", "theaijournal", "synced_ai", "thegradient", "importai", "paperswithcode", "nvidia_blog", "google_ai_blog", "microsoft_ai", "meta_ai", "anthropic_news", "distill", "twomin_papers", "aisupremacy", "singularityhub"],
  science: ["bbc_science", "nytimes_science", "guardian_science", "guardian_space", "npr_science", "sciencedaily", "sciencedaily_health", "sciencedaily_tech", "sciencedaily_environment", "sciencedaily_mind", "nasa", "nasa_image", "newscientist", "phys_org", "phys_org_tech", "phys_org_space", "space_com", "livescience", "iflscience", "sciencealert", "smithsonianmag", "popularmechanics", "popsci", "eos", "quantamagazine", "scienceamerican", "wired_science", "arstechnica_science", "thehindu_science", "dw_science", "cosmosmagazine", "atlasobscura", "discovermagazine", "technologynetworks", "futurism", "nature_news", "science_mag", "cell_press", "newatlas", "labmanager", "sciencenews", "theconversation_sci", "eurekalert", "sciencefocus", "mentalfloss"],
  space: ["nasa", "nasa_image", "spacenews", "nasaspaceflight", "universetoday", "skyandtelescope", "planetary_org", "spacepolicyonline", "spaceflightnow", "space_com", "phys_org_space", "guardian_space", "esa_news", "arianespace"],
  health: ["cnn_health", "nytimes_health", "npr_health", "bbc_health", "who_news", "statnews", "medpagetoday", "healthline", "medicalnewstoday", "webmd_news", "everydayhealth", "health_harvard", "psychologytoday", "medscape", "sciencedaily_health", "guardian_health", "fiercepharma", "healio", "nih_news", "cdc_news", "healtheuropa", "fiercehealthcare", "healthaffairs", "zeenews_health"],
  climate: ["guardian_environment", "guardian_climate", "guardian_animals", "nytimes_climate", "mongabay", "carbonbrief", "climatehome", "treehugger", "insideclimatenews", "ecowatch", "grist", "cleantech", "reneweconomy", "sciencedaily_environment", "desmog", "earthorg", "ensia", "yaleclimateconnections", "greenmatters", "circularonline", "energymonitor", "dw_environment"],
  sports: ["bbc_sport", "bbc_football", "bbc_cricket", "bbc_tennis", "bbc_f1", "bbc_rugby", "bbc_golf", "bbc_boxing", "nytimes_sports", "espn", "espn_football", "espn_nba", "espn_nfl", "espn_mlb", "espn_tennis", "espn_f1", "espn_golf", "espn_mma", "skysports", "skysports_football", "skysports_cricket", "skysports_f1", "skysports_nfl", "skysports_golf", "skysports_boxing", "sportskeeda", "cricinfo", "cricbuzz", "f1", "cbssports", "theathletic", "sbnation", "sportingnews", "bleacherreport", "wrestlinginc", "mmafighting", "marca_en", "si_soccer", "talksport", "sportbible", "olympic_news", "ufc", "pga", "nba_news", "mlb_news", "nhl", "football365", "fourfourtwo", "givemesport", "ndtv_sports", "toi_sports", "hindustantimes_sports", "thehindu_sports", "indianexpress_sports", "news18_sports", "guardian_football", "guardian_cricket", "guardian_tennis", "guardian_rugby", "guardian_golf", "guardian_boxing", "guardian_f1", "dw_sports", "zeenews_sports", "wion_sports"],
  entertainment: ["variety", "hollywoodreporter", "deadline", "tmz", "eonline", "collider", "screenrant", "avclub", "indiewire", "comicbook", "denofgeek", "slashfilm", "cinemablend", "cbr", "giantfreakinrobot", "theplaylist", "filmschoolrejects", "cnn_entertainment", "bbc_entertainment", "nytimes_arts", "nytimes_movies", "nytimes_theater", "guardian_film", "guardian_tv", "toi_entertainment", "hindustantimes_entertainment", "indianexpress_entertainment", "news18_entertainment", "thehindu_entertainment", "tvline", "tvinsider", "paste_tv", "whatsonnetflix", "decider", "gamesradar_movies", "empireonline", "joblo", "vulture", "pajiba", "bloody_disgusting", "thewrap", "movieweb", "wegotthiscovered", "liveforlivemusic", "anime_news", "crunchyroll_news", "wion_entertainment", "zeenews_entertainment", "skynews_entertainment"],
  gaming: ["polygon", "ign", "ign_playstation", "ign_xbox", "ign_nintendo", "ign_pc", "kotaku", "eurogamer", "gamespot", "pcgamer", "rockpapershotgun", "nintendolife", "gamesradar", "pushsquare", "purexbox", "destructoid", "gamedeveloper", "dualshockers", "vg247", "siliconera", "toucharcade", "rpgsite", "gameinformer", "hardcore_gamer", "escapist", "mp1st", "playstationblog", "xbox_news", "nindies", "arstechnica_gaming", "gamingbolt", "twinfinite", "thegamer", "gamerant", "segmentnext", "gamepur", "shacknews"],
  music: ["billboard", "rollingstone", "rollingstone_music", "pitchfork", "nme", "stereogum", "consequenceofsound", "brooklynvegan", "spin", "loudwire", "metal_injection", "edm_com", "guardian_music", "clash_music", "paste_music", "diymagazine", "tinymixtapes", "fact_mag", "npr_music"],
  food: ["eater", "eater_national", "bonappetit", "seriouseats", "foodandwine", "tastingtable", "thespruceeats", "epicurious", "saveur", "food52", "nytimes_food", "guardian_food", "guardian_food2", "thekitchn", "thekitchn2", "cookinglight", "delish", "npr_food", "ndtv_food"],
  travel: ["cnn_travel", "cnn_travel2", "lonelyplanet", "cntraveler", "travelandleisure", "afar", "matadornetwork", "thepointsguy", "nomadicmatt", "skyscanner_news", "nytimes_travel", "nytimes_travel2", "guardian_travel", "guardian_travel2", "fodors", "tourismreview", "breakingtravelnews", "usatoday_travel"],
  automotive: ["motortrend", "caranddriver", "jalopnik", "autoblog", "topgear", "electrek", "insideevs", "thedrive", "roadandtrack", "carscoops", "carbuzz", "greencarreports", "nytimes_automobiles", "arstechnica_cars", "motor1", "autocar", "autoexpress", "drivetribe", "motorauthority", "carthrottle", "ndtv_auto", "carandbike"],
  realestate: ["curbed", "housingwire", "inman", "realtor_com", "nytimes_realestate"],
  education: ["mit_news", "ed_week", "insidehighered", "edsurge", "ted_blog", "edutopia", "campustechnology", "timeshighered", "harvard_gazette", "stanford_news", "oxford_news", "cambridge_news", "bbc_education", "npr_education", "guardian_education", "nytimes_education", "wired_education", "khanacademy_blog", "chronicle_he2", "eschoolnews", "teachthought", "edtechmagazine", "hindustantimes_education", "thehindu_education", "indianexpress_education", "news18_education", "toi_education"],
  law: ["lawfaremedia", "scotusblog", "jurist", "law_com", "techdirt", "eff", "arstechnica_policy"],
  startups: ["techcrunch_startups", "techcrunch_venture", "saastr", "producthunt", "betalist", "startupgrind", "ycombinator_blog", "crunchbase_news", "eu_startups", "yourstory", "economictimes_startups"],
  design: ["uxdesign", "abduzeedo", "creativebloq", "yankodesign", "designboom", "archdaily", "dezeen", "core77", "designmilk", "itsnicethat", "designweek", "wallpaper", "inhabitat", "fastcodesign", "colossal", "booooooom"],
  defense: ["defensenews", "warisboring", "defenseone", "breakingdefense", "militarytimes", "warzone", "armscontrol", "navalnews", "airforcemag"],
  philosophy: ["aeon", "brainpickings", "brainpickings2", "openculture", "dailystoic", "philosophynow", "lithub", "electricliterature", "theparisreview", "nytimes_books", "npr_books", "guardian_books", "plato_stanford", "psyche_aeon", "farnam_street", "npr_culture"],
  personalfinance: ["nerdwallet", "bankrate", "fool", "thebalance", "moneyunder30", "guardian_money", "wise_bread", "thebalance_invest", "daveramsey", "mrmoneymustache", "financialsamurai", "investopedia_news", "moneycontrol_personal", "usatoday_money", "globalnews_money"],
  fashion: ["vogue", "gq", "harpersbazaar", "allure", "refinery29", "highsnobiety", "hypebeast", "complex", "nytimes_fashion", "guardian_fashion", "wwd", "fashionista", "manrepeller", "beautyindependent", "byrdie", "whowhatwear"],
  parenting: ["parents", "todaysparent", "fatherly", "romper", "scarymommy"],
  fitness: ["menshealth", "womenshealth", "runnersworld", "mindbodygreen", "wellandgood"],
  home: ["apartmenttherapy", "bobvila", "thekitchn", "bhg", "dwell", "curbed_design"],
  pets: ["thedodo", "dogster", "catster", "guardian_animals"],
  photography: ["petapixel", "dpreview", "fstoppers", "diyphotography"],
  history: ["historydaily", "historyextra", "warhistoryonline", "nytimes_obituaries", "atlasobscura"],
  lifestyle: ["bustle", "thecut", "manofmany", "coolhunting", "uncrate", "gearpatrol", "thrillist", "popsugar", "thegoodtrade", "minimalismlife", "theeverygirl", "cup_of_jo", "upworthy", "brightly", "guardian_lifestyle", "indianexpress_lifestyle", "hindustantimes_lifestyle", "news18_lifestyle", "toi_life", "wsj_lifestyle", "usatoday_life", "npr_race"],
  media: ["nieman_lab", "poynter", "cjr", "mediaite"],
};

function getCategoryForSource(sourceKey) {
  for (const [cat, keys] of Object.entries(CATEGORIES)) {
    if (keys.includes(sourceKey)) return cat;
  }
  return "uncategorized";
}

function getSourcesForCategory(category) {
  return CATEGORIES[category] || [];
}

function listCategories() {
  return Object.entries(CATEGORIES).map(([name, keys]) => ({
    name,
    count: keys.length,
  }));
}

module.exports = { CATEGORIES, getCategoryForSource, getSourcesForCategory, listCategories };
