// GlobalWire Agent — 700+ curated RSS feeds.
// Heavy redundancy per category ensures fallback coverage.

const SOURCES = {
  // ===================== WORLD / GENERAL NEWS =====================
  bbc: "http://feeds.bbci.co.uk/news/rss.xml",
  bbc_world: "http://feeds.bbci.co.uk/news/world/rss.xml",
  bbc_uk: "http://feeds.bbci.co.uk/news/uk/rss.xml",
  bbc_politics: "http://feeds.bbci.co.uk/news/politics/rss.xml",
  bbc_education: "http://feeds.bbci.co.uk/news/education/rss.xml",
  bbc_asia: "http://feeds.bbci.co.uk/news/world/asia/rss.xml",
  bbc_africa: "http://feeds.bbci.co.uk/news/world/africa/rss.xml",
  bbc_europe: "http://feeds.bbci.co.uk/news/world/europe/rss.xml",
  bbc_middleeast: "http://feeds.bbci.co.uk/news/world/middle_east/rss.xml",
  bbc_latam: "http://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
  cnn: "http://rss.cnn.com/rss/cnn_topstories.rss",
  cnn_world: "http://rss.cnn.com/rss/cnn_world.rss",
  cnn_us: "http://rss.cnn.com/rss/cnn_us.rss",
  cnn_politics: "http://rss.cnn.com/rss/cnn_allpolitics.rss",
  cnn_entertainment: "http://rss.cnn.com/rss/cnn_showbiz.rss",
  cnn_travel: "http://rss.cnn.com/rss/cnn_travel.rss",
  guardian: "https://www.theguardian.com/world/rss",
  guardian_uk: "https://www.theguardian.com/uk-news/rss",
  guardian_us: "https://www.theguardian.com/us-news/rss",
  guardian_opinion: "https://www.theguardian.com/commentisfree/rss",
  guardian_australia: "https://www.theguardian.com/australia-news/rss",
  guardian_europe: "https://www.theguardian.com/world/europe-news/rss",
  guardian_books: "https://www.theguardian.com/books/rss",
  guardian_film: "https://www.theguardian.com/film/rss",
  guardian_music: "https://www.theguardian.com/music/rss",
  guardian_football: "https://www.theguardian.com/football/rss",
  guardian_cricket: "https://www.theguardian.com/sport/cricket/rss",
  guardian_lifestyle: "https://www.theguardian.com/lifeandstyle/rss",
  guardian_education: "https://www.theguardian.com/education/rss",
  aljazeera: "https://www.aljazeera.com/xml/rss/all.xml",
  npr: "https://feeds.npr.org/1001/rss.xml",
  npr_world: "https://feeds.npr.org/1004/rss.xml",
  npr_politics: "https://feeds.npr.org/1014/rss.xml",
  npr_business: "https://feeds.npr.org/1006/rss.xml",
  npr_education: "https://feeds.npr.org/1013/rss.xml",
  npr_books: "https://feeds.npr.org/1032/rss.xml",
  pbs: "https://www.pbs.org/newshour/feeds/rss/headlines",
  skynews: "https://feeds.skynews.com/feeds/rss/world.xml",
  skynews_uk: "https://feeds.skynews.com/feeds/rss/uk.xml",
  skynews_business: "https://feeds.skynews.com/feeds/rss/business.xml",
  skynews_tech: "https://feeds.skynews.com/feeds/rss/technology.xml",
  dw: "https://rss.dw.com/rdf/rss-en-all",
  dw_asia: "https://rss.dw.com/rdf/rss-en-asia",
  dw_europe: "https://rss.dw.com/rdf/rss-en-eu",
  dw_science: "https://rss.dw.com/rdf/rss-en-science",
  dw_business: "https://rss.dw.com/rdf/rss-en-bus",
  france24: "https://www.france24.com/en/rss",
  nhk: "https://www3.nhk.or.jp/rss/news/cat0.xml",
  axios: "https://api.axios.com/feed/",
  thehill: "https://thehill.com/feed/",
  nytimes: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
  nytimes_world: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
  nytimes_us: "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
  nytimes_politics: "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
  nytimes_opinion: "https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml",
  nytimes_arts: "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
  nytimes_books: "https://rss.nytimes.com/services/xml/rss/nyt/Books.xml",
  nytimes_movies: "https://rss.nytimes.com/services/xml/rss/nyt/Movies.xml",
  nytimes_travel: "https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml",
  nytimes_realestate: "https://rss.nytimes.com/services/xml/rss/nyt/RealEstate.xml",
  nytimes_fashion: "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml",
  nytimes_food: "https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml",
  nytimes_education: "https://rss.nytimes.com/services/xml/rss/nyt/Education.xml",
  nytimes_climate: "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml",
  foxnews: "https://moxie.foxnews.com/google-publisher/latest.xml",
  abcnews: "https://abcnews.go.com/abcnews/topstories",
  cbsnews: "https://www.cbsnews.com/latest/rss/main",
  vox: "https://www.vox.com/rss/index.xml",
  slate: "https://slate.com/feeds/all.rss",
  newsweek: "https://www.newsweek.com/rss",
  huffpost: "https://www.huffpost.com/section/front-page/feed",
  time: "https://time.com/feed/",
  theintercept: "https://theintercept.com/feed/?rss",
  thedailybeast: "https://feeds.thedailybeast.com/rss/articles",
  salon: "https://www.salon.com/feed/",
  motherjones: "https://www.motherjones.com/feed/",
  reason: "https://reason.com/feed/",
  foreignpolicy: "https://foreignpolicy.com/feed/",
  theatlantic: "https://www.theatlantic.com/feed/all/",
  csmonitor: "https://www.csmonitor.com/rss/all",
  propublica: "https://feeds.propublica.org/propublica/main",
  theconversation: "https://theconversation.com/articles.atom",
  globalvoices: "https://globalvoices.org/feed/",

  // ===================== ASIA-PACIFIC =====================
  scmp: "https://www.scmp.com/rss/91/feed",
  straitstimes: "https://www.straitstimes.com/news/world/rss.xml",
  abcaus: "https://www.abc.net.au/news/feed/51120/rss.xml",
  abcaus_world: "https://www.abc.net.au/news/feed/2942460/rss.xml",
  cbcca: "https://www.cbc.ca/cmlink/rss-topstories",
  cbcca_world: "https://www.cbc.ca/cmlink/rss-world",
  cbcca_tech: "https://www.cbc.ca/cmlink/rss-technology",
  cbcca_politics: "https://www.cbc.ca/cmlink/rss-politics",
  cbcca_business: "https://www.cbc.ca/cmlink/rss-business",
  japantimes: "https://www.japantimes.co.jp/feed/",
  bangkokpost: "https://www.bangkokpost.com/rss/data/topstories.xml",
  channelnewsasia: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
  smh: "https://www.smh.com.au/rss/feed.xml",
  globalnews_ca: "https://globalnews.ca/feed/",
  stuff_nz: "https://www.stuff.co.nz/rss",
  dawn: "https://www.dawn.com/feeds/home",
  dailystar_bd: "https://www.thedailystar.net/frontpage/rss.xml",
  inquirer_ph: "https://newsinfo.inquirer.net/feed",

  // ===================== INDIA =====================
  ndtv: "https://feeds.feedburner.com/ndtvnews-top-stories",
  ndtv_india: "https://feeds.feedburner.com/ndtvnews-india-news",
  ndtv_world: "https://feeds.feedburner.com/ndtvnews-world-news",
  ndtv_sports: "https://feeds.feedburner.com/ndtvsports-latest",
  ndtv_tech: "https://feeds.feedburner.com/gadgets360-latest",
  toi: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
  toi_world: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
  toi_tech: "https://timesofindia.indiatimes.com/rssfeeds/66949542.cms",
  toi_sports: "https://timesofindia.indiatimes.com/rssfeeds/4719148.cms",
  toi_entertainment: "https://timesofindia.indiatimes.com/rssfeeds/1081479906.cms",
  toi_business: "https://timesofindia.indiatimes.com/rssfeeds/1898055.cms",
  toi_city: "https://timesofindia.indiatimes.com/rssfeeds/913168846.cms",
  toi_life: "https://timesofindia.indiatimes.com/rssfeeds/2886704.cms",
  hindustantimes: "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
  hindustantimes_world: "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml",
  hindustantimes_sports: "https://www.hindustantimes.com/feeds/rss/sports/rssfeed.xml",
  hindustantimes_entertainment: "https://www.hindustantimes.com/feeds/rss/entertainment/rssfeed.xml",
  hindustantimes_tech: "https://www.hindustantimes.com/feeds/rss/technology/rssfeed.xml",
  thehindu: "https://www.thehindu.com/news/national/feeder/default.rss",
  thehindu_international: "https://www.thehindu.com/news/international/feeder/default.rss",
  thehindu_sports: "https://www.thehindu.com/sport/feeder/default.rss",
  thehindu_entertainment: "https://www.thehindu.com/entertainment/feeder/default.rss",
  thehindu_science: "https://www.thehindu.com/sci-tech/science/feeder/default.rss",
  thehindu_tech: "https://www.thehindu.com/sci-tech/technology/feeder/default.rss",
  indianexpress: "https://indianexpress.com/section/india/feed/",
  indianexpress_world: "https://indianexpress.com/section/world/feed/",
  indianexpress_tech: "https://indianexpress.com/section/technology/feed/",
  indianexpress_sports: "https://indianexpress.com/section/sports/feed/",
  indianexpress_entertainment: "https://indianexpress.com/section/entertainment/feed/",
  indianexpress_lifestyle: "https://indianexpress.com/section/lifestyle/feed/",
  economictimes: "https://economictimes.indiatimes.com/rssfeedstopstories.cms",
  economictimes_tech: "https://economictimes.indiatimes.com/tech/rssfeeds/13357270.cms",
  economictimes_markets: "https://economictimes.indiatimes.com/markets/rssfeeds/1977021501.cms",
  economictimes_startups: "https://economictimes.indiatimes.com/small-biz/rssfeeds/67560513.cms",
  livemint: "https://www.livemint.com/rss/news",
  livemint_tech: "https://www.livemint.com/rss/technology",
  livemint_markets: "https://www.livemint.com/rss/markets",
  indiatoday: "https://www.indiatoday.in/rss/home",
  indiatoday_india: "https://www.indiatoday.in/rss/1",
  indiatoday_tech: "https://www.indiatoday.in/rss/30",
  businessstandard: "https://www.business-standard.com/rss/home_page_top_stories.rss",
  businessstandard_markets: "https://www.business-standard.com/rss/markets-106.rss",
  news18: "https://www.news18.com/commonfeeds/v1/eng/rss/india.xml",
  news18_world: "https://www.news18.com/commonfeeds/v1/eng/rss/world.xml",
  news18_tech: "https://www.news18.com/commonfeeds/v1/eng/rss/tech.xml",
  news18_sports: "https://www.news18.com/commonfeeds/v1/eng/rss/cricket.xml",
  news18_entertainment: "https://www.news18.com/commonfeeds/v1/eng/rss/entertainment.xml",
  dnaindia: "https://www.dnaindia.com/feeds/india.xml",
  oneindia: "https://www.oneindia.com/rss/news-india-fb.xml",
  tribuneindia: "https://www.tribuneindia.com/rss/feed",
  swarajya: "https://swarajyamag.com/feed",
  scroll_in: "https://scroll.in/rss/feed",
  thequint: "https://www.thequint.com/quintlab/rss-feeds/the-quint-top-stories.xml",

  // ===================== MIDDLE EAST =====================
  jerusalempost: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
  arabnews: "https://www.arabnews.com/rss.xml",
  thenationalnews: "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml",
  middleeasteye: "https://www.middleeasteye.net/rss",
  almonitor: "https://www.al-monitor.com/rss",

  // ===================== EUROPE =====================
  lemonde: "https://www.lemonde.fr/en/rss/une.xml",
  derspiegel: "https://www.spiegel.de/international/index.rss",
  elpais: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
  euronews: "https://www.euronews.com/rss",
  irish_times: "https://www.irishtimes.com/cmlink/news-1.1319192",
  dutchnews: "https://www.dutchnews.nl/feed/",
  thelocal_se: "https://feeds.thelocal.com/rss/se",
  thelocal_de: "https://feeds.thelocal.com/rss/de",
  thelocal_fr: "https://feeds.thelocal.com/rss/fr",
  thelocal_it: "https://feeds.thelocal.com/rss/it",
  thelocal_es: "https://feeds.thelocal.com/rss/es",
  thelocal_no: "https://feeds.thelocal.com/rss/no",
  thelocal_at: "https://feeds.thelocal.com/rss/at",
  thelocal_ch: "https://feeds.thelocal.com/rss/ch",
  thelocal_dk: "https://feeds.thelocal.com/rss/dk",
  rte: "https://www.rte.ie/news/rss/news-headlines.xml",
  swissinfo: "https://www.swissinfo.ch/eng/rss",
  balkan_insight: "https://balkaninsight.com/feed/",
  politico_eu: "https://www.politico.eu/feed/",

  // ===================== LATIN AMERICA =====================
  mercopress: "https://en.mercopress.com/rss/",
  batimes: "https://www.batimes.com.ar/feed",
  ticotimes: "https://ticotimes.net/feed",
  brasilwire: "https://www.brasilwire.com/feed/",

  // ===================== AFRICA =====================
  allafrica: "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
  news24_sa: "https://feeds.news24.com/articles/news24/TopStories/rss",
  theeastafrican: "https://www.theeastafrican.co.ke/tea/rss",
  citizen_za: "https://www.citizen.co.za/feed/",
  punch_ng: "https://punchng.com/feed/",
  premiumtimes_ng: "https://www.premiumtimesng.com/feed",
  nation_ke: "https://nation.africa/rss.xml",

  // ===================== BUSINESS / FINANCE =====================
  bloomberg: "https://feeds.bloomberg.com/markets/news.rss",
  cnbc: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",
  cnbc_world: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362",
  cnbc_tech: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910",
  cnbc_finance: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664",
  cnbc_earnings: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15839135",
  marketwatch: "https://www.marketwatch.com/rss/topstories",
  marketwatch_markets: "https://www.marketwatch.com/rss/marketpulse",
  businessinsider: "https://www.businessinsider.com/rss",
  ft: "https://www.ft.com/rss/home",
  moneycontrol: "https://www.moneycontrol.com/rss/latestnews.xml",
  moneycontrol_markets: "https://www.moneycontrol.com/rss/marketreports.xml",
  moneycontrol_business: "https://www.moneycontrol.com/rss/business.xml",
  moneycontrol_tech: "https://www.moneycontrol.com/rss/techinnovation.xml",
  seeking_alpha: "https://seekingalpha.com/market_currents.xml",
  yahoo_finance: "https://finance.yahoo.com/news/rssindex",
  nytimes_business: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
  nytimes_economy: "https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml",
  guardian_business: "https://www.theguardian.com/uk/business/rss",
  guardian_money: "https://www.theguardian.com/money/rss",
  investing_com: "https://www.investing.com/rss/news.rss",
  fortune: "https://fortune.com/feed/",
  fastcompany: "https://www.fastcompany.com/latest/rss",
  entrepreneur: "https://www.entrepreneur.com/latest.rss",
  inc: "https://www.inc.com/rss/",
  hbr: "https://feeds.hbr.org/harvardbusiness",

  // ===================== CRYPTO / WEB3 / FINTECH =====================
  coindesk: "https://www.coindesk.com/arc/outboundfeeds/rss/",
  cointelegraph: "https://cointelegraph.com/rss",
  theblock: "https://www.theblock.co/rss.xml",
  decrypt: "https://decrypt.co/feed",
  bitcoinmagazine: "https://bitcoinmagazine.com/.rss/full/",
  cryptoslate: "https://cryptoslate.com/feed/",
  beincrypto: "https://beincrypto.com/feed/",
  ambcrypto: "https://ambcrypto.com/feed/",
  cryptopotato: "https://cryptopotato.com/feed/",
  defiant: "https://thedefiant.io/feed",
  blockonomi: "https://blockonomi.com/feed/",
  newsbtc: "https://www.newsbtc.com/feed/",
  dailyhodl: "https://dailyhodl.com/feed/",
  unchained: "https://unchainedcrypto.com/feed/",
  bankless: "https://www.bankless.com/rss",

  // ===================== TECHNOLOGY =====================
  bbc_tech: "http://feeds.bbci.co.uk/news/technology/rss.xml",
  cnn_tech: "http://rss.cnn.com/rss/cnn_tech.rss",
  guardian_tech: "https://www.theguardian.com/uk/technology/rss",
  nytimes_tech: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
  techcrunch: "https://techcrunch.com/feed/",
  techcrunch_apps: "https://techcrunch.com/category/apps/feed/",
  techcrunch_gadgets: "https://techcrunch.com/category/gadgets/feed/",
  theverge: "https://www.theverge.com/rss/index.xml",
  wired: "https://www.wired.com/feed/rss",
  wired_science: "https://www.wired.com/feed/category/science/latest/rss",
  wired_business: "https://www.wired.com/feed/category/business/latest/rss",
  wired_gear: "https://www.wired.com/feed/category/gear/latest/rss",
  arstechnica: "https://feeds.arstechnica.com/arstechnica/index",
  arstechnica_science: "https://feeds.arstechnica.com/arstechnica/science",
  arstechnica_gadgets: "https://feeds.arstechnica.com/arstechnica/gadgets",
  engadget: "https://www.engadget.com/rss.xml",
  hackernews: "https://hnrss.org/frontpage",
  hackernews_best: "https://hnrss.org/best",
  mashable: "https://mashable.com/feeds/rss/all",
  zdnet: "https://www.zdnet.com/news/rss.xml",
  tomshardware: "https://www.tomshardware.com/feeds/all",
  androidcentral: "https://www.androidcentral.com/feed",
  androidauthority: "https://www.androidauthority.com/feed/",
  nine_to_five_mac: "https://9to5mac.com/feed/",
  nine_to_five_google: "https://9to5google.com/feed/",
  thenextweb: "https://thenextweb.com/feed/",
  gizmodo: "https://gizmodo.com/feed",
  cnet: "https://www.cnet.com/rss/news/",
  techradar: "https://www.techradar.com/rss",
  theregister: "https://www.theregister.com/headlines.atom",
  slashdot: "https://rss.slashdot.org/Slashdot/slashdotMain",
  pcworld: "https://www.pcworld.com/feed",
  macrumors: "https://feeds.macrumors.com/MacRumors-All",
  mit_tech_review: "https://www.technologyreview.com/feed/",
  howtogeek: "https://www.howtogeek.com/feed/",
  xda: "https://www.xda-developers.com/feed/",
  windowscentral: "https://www.windowscentral.com/feed",
  bleepingcomputer: "https://www.bleepingcomputer.com/feed/",
  digitaltrends: "https://www.digitaltrends.com/feed/",
  lifehacker: "https://lifehacker.com/feed/rss",
  makeuseof: "https://www.makeuseof.com/feed/",
  appleinsider: "https://appleinsider.com/rss/news/",
  phonearena: "https://www.phonearena.com/feed",
  gsmarena: "https://www.gsmarena.com/rss-news-reviews.php3",
  notebookcheck: "https://www.notebookcheck.net/News.152.0.html?rss",
  anandtech: "https://www.anandtech.com/rss/",
  protocoldotcom: "https://www.protocol.com/feeds/feed.rss",
  restofworld: "https://restofworld.org/feed/",

  // ===================== CYBERSECURITY =====================
  darkreading: "https://www.darkreading.com/rss.xml",
  threatpost: "https://threatpost.com/feed/",
  krebsonsecurity: "https://krebsonsecurity.com/feed/",
  securityweek: "https://www.securityweek.com/feed/",
  thehackernews_sec: "https://feeds.feedburner.com/TheHackersNews",
  naked_security: "https://nakedsecurity.sophos.com/feed/",
  hackernews_security: "https://hnrss.org/newest?q=security",
  schneier: "https://www.schneier.com/feed/atom/",
  cyberscoop: "https://cyberscoop.com/feed/",
  zdnet_security: "https://www.zdnet.com/topic/security/rss.xml",
  tripwire: "https://www.tripwire.com/state-of-security/feed",

  // ===================== PROGRAMMING / DEV =====================
  dev_to: "https://dev.to/feed/",
  dev_to_top: "https://dev.to/feed/top/week",
  hackernoon: "https://hackernoon.com/feed",
  smashingmag: "https://www.smashingmagazine.com/feed/",
  css_tricks: "https://css-tricks.com/feed/",
  sitepoint: "https://www.sitepoint.com/feed/",
  infoq: "https://feed.infoq.com/",
  dzone: "https://feeds.dzone.com/home",
  github_blog: "https://github.blog/feed/",
  github_changelog: "https://github.blog/changelog/feed/",
  freecodecamp: "https://www.freecodecamp.org/news/rss/",
  stackoverflow_blog: "https://stackoverflow.blog/feed/",
  devops_com: "https://devops.com/feed/",
  thenewstack: "https://thenewstack.io/feed/",
  hashnode: "https://hashnode.com/n/general-programming/rss",
  medium_programming: "https://medium.com/feed/tag/programming",
  logrocket: "https://blog.logrocket.com/feed/",

  // ===================== AI / MACHINE LEARNING =====================
  openai_blog: "https://openai.com/blog/rss.xml",
  deepmind_blog: "https://deepmind.google/blog/rss.xml",
  mlnews: "https://machinelearningmastery.com/feed/",
  towardsdatascience: "https://towardsdatascience.com/feed",
  analyticsvidhya: "https://www.analyticsvidhya.com/feed/",
  kdnuggets: "https://www.kdnuggets.com/feed",
  venturebeat_ai: "https://venturebeat.com/category/ai/feed/",
  huggingface_blog: "https://huggingface.co/blog/feed.xml",
  aitrends: "https://aitrends.com/feed/",
  marktechpost: "https://www.marktechpost.com/feed/",
  aibusiness: "https://aibusiness.com/rss.xml",
  aimag: "https://aimagazine.com/rss.xml",
  unite_ai: "https://www.unite.ai/feed/",
  datasciencecentral: "https://www.datasciencecentral.com/feed/",
  medium_ai: "https://medium.com/feed/tag/artificial-intelligence",

  // ===================== SCIENCE =====================
  bbc_science: "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
  nytimes_science: "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
  guardian_science: "https://www.theguardian.com/science/rss",
  npr_science: "https://feeds.npr.org/1007/rss.xml",
  sciencedaily: "https://www.sciencedaily.com/rss/all.xml",
  sciencedaily_health: "https://www.sciencedaily.com/rss/health_medicine.xml",
  sciencedaily_tech: "https://www.sciencedaily.com/rss/matter_energy.xml",
  sciencedaily_environment: "https://www.sciencedaily.com/rss/earth_climate.xml",
  nasa: "https://www.nasa.gov/rss/dyn/breaking_news.rss",
  nasa_image: "https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss",
  newscientist: "https://www.newscientist.com/feed/home/",
  phys_org: "https://phys.org/rss-feed/",
  phys_org_tech: "https://phys.org/rss-feed/technology-news/",
  phys_org_space: "https://phys.org/rss-feed/space-news/",
  space_com: "https://www.space.com/feeds/all",
  livescience: "https://www.livescience.com/feeds/all",
  iflscience: "https://www.iflscience.com/feed",
  sciencealert: "https://www.sciencealert.com/feed",
  smithsonianmag: "https://www.smithsonianmag.com/rss/latest_articles/",
  popularmechanics: "https://www.popularmechanics.com/rss/",
  popsci: "https://www.popsci.com/feed/",
  eos: "https://eos.org/feed",
  quantamagazine: "https://api.quantamagazine.org/feed/",
  scienceamerican: "https://www.scientificamerican.com/feed/",

  // ===================== SPACE / ASTRONOMY =====================
  spacenews: "https://spacenews.com/feed/",
  nasaspaceflight: "https://www.nasaspaceflight.com/feed/",
  universetoday: "https://www.universetoday.com/feed/",
  skyandtelescope: "https://skyandtelescope.org/feed/",
  planetary_org: "https://www.planetary.org/feed",
  spacepolicyonline: "https://spacepolicyonline.com/feed/",
  spaceflightnow: "https://spaceflightnow.com/feed/",

  // ===================== HEALTH / MEDICINE =====================
  cnn_health: "http://rss.cnn.com/rss/cnn_health.rss",
  nytimes_health: "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
  npr_health: "https://feeds.npr.org/1128/rss.xml",
  who_news: "https://www.who.int/rss-feeds/news-english.xml",
  statnews: "https://www.statnews.com/feed/",
  medpagetoday: "https://www.medpagetoday.com/rss/headlines.xml",
  healthline: "https://www.healthline.com/rss",
  medicalnewstoday: "https://rss.medicalnewstoday.com/featurednews.xml",
  webmd_news: "https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC",
  everydayhealth: "https://www.everydayhealth.com/rss/",
  health_harvard: "https://www.health.harvard.edu/blog/feed",
  psychologytoday: "https://www.psychologytoday.com/intl/blog/feed",
  medscape: "https://www.medscape.com/cx/rssfeeds/2685.xml",

  // ===================== ENVIRONMENT / CLIMATE =====================
  guardian_environment: "https://www.theguardian.com/environment/rss",
  guardian_climate: "https://www.theguardian.com/environment/climate-crisis/rss",
  mongabay: "https://news.mongabay.com/feed/",
  carbonbrief: "https://www.carbonbrief.org/feed/",
  climatehome: "https://www.climatechangenews.com/feed/",
  treehugger: "https://www.treehugger.com/feeds/all",
  insideclimatenews: "https://insideclimatenews.org/feed/",
  ecowatch: "https://www.ecowatch.com/rss",
  grist: "https://grist.org/feed/",
  cleantech: "https://cleantechnica.com/feed/",
  reneweconomy: "https://reneweconomy.com.au/feed/",

  // ===================== SPORTS =====================
  bbc_sport: "https://feeds.bbci.co.uk/sport/rss.xml",
  bbc_football: "https://feeds.bbci.co.uk/sport/football/rss.xml",
  bbc_cricket: "https://feeds.bbci.co.uk/sport/cricket/rss.xml",
  bbc_tennis: "https://feeds.bbci.co.uk/sport/tennis/rss.xml",
  bbc_f1: "https://feeds.bbci.co.uk/sport/formula1/rss.xml",
  bbc_rugby: "https://feeds.bbci.co.uk/sport/rugby-union/rss.xml",
  bbc_golf: "https://feeds.bbci.co.uk/sport/golf/rss.xml",
  bbc_boxing: "https://feeds.bbci.co.uk/sport/boxing/rss.xml",
  nytimes_sports: "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
  espn: "https://www.espn.com/espn/rss/news",
  espn_football: "https://www.espn.com/espn/rss/soccer/news",
  espn_nba: "https://www.espn.com/espn/rss/nba/news",
  espn_nfl: "https://www.espn.com/espn/rss/nfl/news",
  espn_mlb: "https://www.espn.com/espn/rss/mlb/news",
  espn_tennis: "https://www.espn.com/espn/rss/tennis/news",
  skysports: "https://www.skysports.com/rss/12040",
  skysports_football: "https://www.skysports.com/rss/12040/12098",
  skysports_cricket: "https://www.skysports.com/rss/12040/12123",
  skysports_f1: "https://www.skysports.com/rss/12040/12433",
  sportskeeda: "https://www.sportskeeda.com/feed",
  cricinfo: "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
  f1: "https://www.formula1.com/content/fom-website/en/latest/all.xml",
  cbssports: "https://www.cbssports.com/rss/headlines/",
  theathletic: "https://theathletic.com/feed/",
  sbnation: "https://www.sbnation.com/rss/current",
  sportingnews: "https://www.sportingnews.com/us/rss",
  bleacherreport: "https://bleacherreport.com/articles/feed",
  wrestlinginc: "https://www.wrestlinginc.com/feed/",
  mmafighting: "https://www.mmafighting.com/rss/current",
  marca_en: "https://e00-marca.uecdn.es/rss/en/main.xml",

  // ===================== ENTERTAINMENT / CULTURE =====================
  variety: "https://variety.com/feed/",
  hollywoodreporter: "https://www.hollywoodreporter.com/feed/",
  deadline: "https://deadline.com/feed/",
  tmz: "https://www.tmz.com/rss.xml",
  eonline: "https://www.eonline.com/syndication/feeds/rssfeeds/topstories.xml",
  collider: "https://collider.com/feed/",
  screenrant: "https://screenrant.com/feed/",
  avclub: "https://www.avclub.com/rss",
  indiewire: "https://www.indiewire.com/feed/",
  comicbook: "https://comicbook.com/feed/",
  denofgeek: "https://www.denofgeek.com/feed/",
  slashfilm: "https://www.slashfilm.com/feed/",
  cinemablend: "https://www.cinemablend.com/rss/topic/news/all",
  cbr: "https://www.cbr.com/feed/",
  giantfreakinrobot: "https://www.giantfreakinrobot.com/feed",
  theplaylist: "https://theplaylist.net/feed/",
  filmschoolrejects: "https://filmschoolrejects.com/feed/",

  // ===================== GAMING =====================
  polygon: "https://www.polygon.com/rss/index.xml",
  ign: "https://feeds.ign.com/ign/all",
  ign_playstation: "https://feeds.ign.com/ign/playstation-articles",
  ign_xbox: "https://feeds.ign.com/ign/xbox-articles",
  ign_nintendo: "https://feeds.ign.com/ign/nintendo-articles",
  ign_pc: "https://feeds.ign.com/ign/pc-articles",
  kotaku: "https://kotaku.com/feed",
  eurogamer: "https://www.eurogamer.net/feed",
  gamespot: "https://www.gamespot.com/feeds/mashup/",
  pcgamer: "https://www.pcgamer.com/rss/",
  rockpapershotgun: "https://www.rockpapershotgun.com/feed",
  nintendolife: "https://www.nintendolife.com/feeds/latest",
  gamesradar: "https://www.gamesradar.com/rss/",
  pushsquare: "https://www.pushsquare.com/feeds/latest",
  purexbox: "https://www.purexbox.com/feeds/latest",
  destructoid: "https://www.destructoid.com/feed/",
  gamedeveloper: "https://www.gamedeveloper.com/rss.xml",
  dualshockers: "https://www.dualshockers.com/feed/",
  vg247: "https://www.vg247.com/feed",
  siliconera: "https://www.siliconera.com/feed/",
  toucharcade: "https://toucharcade.com/feed/",
  rpgsite: "https://www.rpgsite.net/feed",

  // ===================== MUSIC =====================
  billboard: "https://www.billboard.com/feed/",
  rollingstone: "https://www.rollingstone.com/feed/",
  rollingstone_music: "https://www.rollingstone.com/music/feed/",
  pitchfork: "https://pitchfork.com/feed/feed-news/rss",
  nme: "https://www.nme.com/feed",
  stereogum: "https://www.stereogum.com/feed/",
  consequenceofsound: "https://consequence.net/feed/",
  brooklynvegan: "https://www.brooklynvegan.com/feed/",
  spin: "https://www.spin.com/feed/",
  loudwire: "https://loudwire.com/feed/",
  metal_injection: "https://metalinjection.net/feed",
  edm_com: "https://edm.com/feed",

  // ===================== FOOD / COOKING =====================
  eater: "https://www.eater.com/rss/index.xml",
  bonappetit: "https://www.bonappetit.com/feed/rss",
  seriouseats: "https://www.seriouseats.com/feed",
  foodandwine: "https://www.foodandwine.com/feeds/all",
  tastingtable: "https://www.tastingtable.com/feed",
  thespruceeats: "https://www.thespruceeats.com/rss",
  epicurious: "https://www.epicurious.com/feed/rss",
  saveur: "https://www.saveur.com/feed/",
  food52: "https://food52.com/blog.rss",

  // ===================== TRAVEL =====================
  cnn_travel2: "http://rss.cnn.com/rss/cnn_travel.rss",
  lonelyplanet: "https://www.lonelyplanet.com/blog/feed/atom",
  cntraveler: "https://www.cntraveler.com/feed/rss",
  travelandleisure: "https://www.travelandleisure.com/feeds/all",
  afar: "https://www.afar.com/feed",
  matadornetwork: "https://matadornetwork.com/feed/",
  thepointsguy: "https://thepointsguy.com/feed/",
  nomadicmatt: "https://www.nomadicmatt.com/feed/",
  skyscanner_news: "https://www.skyscanner.net/news/feed/",

  // ===================== AUTOMOTIVE =====================
  motortrend: "https://www.motortrend.com/feed/",
  caranddriver: "https://www.caranddriver.com/rss/all.xml/",
  jalopnik: "https://jalopnik.com/feed",
  autoblog: "https://www.autoblog.com/rss.xml",
  topgear: "https://www.topgear.com/rss",
  electrek: "https://electrek.co/feed/",
  insideevs: "https://insideevs.com/rss/news/all/",
  thedrive: "https://www.thedrive.com/feed",
  roadandtrack: "https://www.roadandtrack.com/rss/",
  carscoops: "https://www.carscoops.com/feed/",
  carbuzz: "https://carbuzz.com/feed",
  greencarreports: "https://www.greencarreports.com/rss/news",

  // ===================== REAL ESTATE / HOUSING =====================
  curbed: "https://www.curbed.com/rss/index.xml",
  housingwire: "https://www.housingwire.com/feed/",
  inman: "https://www.inman.com/feed/",
  realtor_com: "https://www.realtor.com/news/feed/",

  // ===================== EDUCATION / RESEARCH =====================
  mit_news: "https://news.mit.edu/rss/feed",
  ed_week: "https://www.edweek.org/feed",
  insidehighered: "https://www.insidehighered.com/rss/feed",
  edsurge: "https://www.edsurge.com/rss",
  ted_blog: "https://blog.ted.com/feed/",
  edutopia: "https://www.edutopia.org/rss.xml",
  campustechnology: "https://campustechnology.com/rss-feeds/columns.aspx",
  timeshighered: "https://www.timeshighereducation.com/rss",
  harvard_gazette: "https://news.harvard.edu/gazette/feed/",
  stanford_news: "https://news.stanford.edu/feed/",
  oxford_news: "https://www.ox.ac.uk/news/feed",
  cambridge_news: "https://www.cam.ac.uk/news/feed",

  // ===================== LAW / POLICY =====================
  lawfaremedia: "https://www.lawfaremedia.org/feed",
  scotusblog: "https://www.scotusblog.com/feed/",
  jurist: "https://www.jurist.org/feed/",
  law_com: "https://www.law.com/feed/",
  techdirt: "https://www.techdirt.com/feed/",
  eff: "https://www.eff.org/rss/updates.xml",

  // ===================== STARTUPS / VENTURE =====================
  techcrunch_startups: "https://techcrunch.com/category/startups/feed/",
  techcrunch_venture: "https://techcrunch.com/category/venture/feed/",
  saastr: "https://www.saastr.com/feed/",
  producthunt: "https://www.producthunt.com/feed",
  betalist: "https://betalist.com/feed",
  startupgrind: "https://www.startupgrind.com/feed/",
  ycombinator_blog: "https://www.ycombinator.com/blog/rss/",
  crunchbase_news: "https://news.crunchbase.com/feed/",
  eu_startups: "https://www.eu-startups.com/feed/",
  yourstory: "https://yourstory.com/feed",

  // ===================== DESIGN / UX =====================
  uxdesign: "https://uxdesign.cc/feed",
  abduzeedo: "https://abduzeedo.com/rss.xml",
  creativebloq: "https://www.creativebloq.com/feed",
  yankodesign: "https://www.yankodesign.com/feed/",
  designboom: "https://www.designboom.com/feed/",
  archdaily: "https://www.archdaily.com/feed",
  dezeen: "https://www.dezeen.com/feed/",
  core77: "https://www.core77.com/RSS",
  designmilk: "https://design-milk.com/feed/",
  itsnicethat: "https://www.itsnicethat.com/rss",
  designweek: "https://www.designweek.co.uk/feed/",

  // ===================== MILITARY / DEFENSE =====================
  defensenews: "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml",
  warisboring: "https://warisboring.com/feed/",
  defenseone: "https://www.defenseone.com/rss/",
  breakingdefense: "https://breakingdefense.com/feed/",
  militarytimes: "https://www.militarytimes.com/arc/outboundfeeds/rss/?outputType=xml",

  // ===================== PHILOSOPHY / HUMANITIES =====================
  aeon: "https://aeon.co/feed.rss",
  brainpickings: "https://feeds.feedburner.com/brainpickings/rss",
  openculture: "https://www.openculture.com/feed",
  dailystoic: "https://dailystoic.com/feed/",
  philosophynow: "https://philosophynow.org/feed",
  lithub: "https://lithub.com/feed/",
  electricliterature: "https://electricliterature.com/feed/",
  theparisreview: "https://www.theparisreview.org/blog/feed/",

  // ===================== PERSONAL FINANCE =====================
  nerdwallet: "https://www.nerdwallet.com/blog/feed/",
  bankrate: "https://www.bankrate.com/rss/",
  fool: "https://www.fool.com/feeds/index.aspx",
  thebalance: "https://www.thebalancemoney.com/rss",
  moneyunder30: "https://www.moneyunder30.com/feed",

  // ===================== FASHION / BEAUTY =====================
  vogue: "https://www.vogue.com/feed/rss",
  gq: "https://www.gq.com/feed/rss",
  harpersbazaar: "https://www.harpersbazaar.com/rss/all.xml/",
  allure: "https://www.allure.com/feed/rss",
  refinery29: "https://www.refinery29.com/rss.xml",
  highsnobiety: "https://www.highsnobiety.com/feed/",
  hypebeast: "https://hypebeast.com/feed",
  complex: "https://www.complex.com/feed/",

  // ===================== PARENTING / FAMILY =====================
  parents: "https://www.parents.com/feed/",
  todaysparent: "https://www.todaysparent.com/feed/",
  fatherly: "https://www.fatherly.com/rss",
  romper: "https://www.romper.com/rss",
  scarymommy: "https://www.scarymommy.com/rss",

  // ===================== FITNESS / WELLNESS =====================
  menshealth: "https://www.menshealth.com/rss/all.xml/",
  womenshealth: "https://www.womenshealthmag.com/rss/all.xml/",
  runnersworld: "https://www.runnersworld.com/rss/all.xml/",
  mindbodygreen: "https://www.mindbodygreen.com/rss",
  wellandgood: "https://www.wellandgood.com/feed/",

  // ===================== HOME / DIY =====================
  apartmenttherapy: "https://www.apartmenttherapy.com/feed",
  bobvila: "https://www.bobvila.com/feed",
  thekitchn: "https://www.thekitchn.com/feed",
  bhg: "https://www.bhg.com/rss/all.xml/",
  dwell: "https://www.dwell.com/feed",

  // ===================== PETS / ANIMALS =====================
  thedodo: "https://www.thedodo.com/rss",
  dogster: "https://www.dogster.com/feed",
  catster: "https://www.catster.com/feed",

  // ===================== WEATHER =====================
  weather_com: "https://weather.com/feeds/rss",
  accuweather: "https://www.accuweather.com/en/rss/weather-news.xml",

  // ===================== HISTORY =====================
  historydaily: "https://historydaily.org/feed",
  historyextra: "https://www.historyextra.com/feed/",
  warhistoryonline: "https://www.warhistoryonline.com/feed",

  // ===================== PHOTOGRAPHY =====================
  petapixel: "https://petapixel.com/feed/",
  dpreview: "https://www.dpreview.com/feeds/news.xml",
  fstoppers: "https://fstoppers.com/rss.xml",
  diyphotography: "https://www.diyphotography.net/feed/",

  // ===================== MORE WORLD / GENERAL =====================
  dailymail: "https://www.dailymail.co.uk/articles.rss",
  mirror_uk: "https://www.mirror.co.uk/all-about/rss.xml",
  metro_uk: "https://metro.co.uk/feed/",
  thesun: "https://www.thesun.co.uk/feed/",
  usatoday_world: "https://rssfeeds.usatoday.com/usatodaycomworld-topstories",
  usatoday_tech: "https://rssfeeds.usatoday.com/usatodaycomtech-topstories",
  usatoday_sports: "https://rssfeeds.usatoday.com/usatodaycomsports-topstories",
  usatoday_money: "https://rssfeeds.usatoday.com/usatodaycommoney-topstories",
  usatoday_life: "https://rssfeeds.usatoday.com/usatodaycomlife-topstories",
  usatoday_travel: "https://rssfeeds.usatoday.com/usatodaycomtravel-topstories",
  rt_news: "https://www.rt.com/rss/",
  xinhua: "https://www.xinhuanet.com/english/rss/worldrss.xml",
  tass: "https://tass.com/rss/v2.xml",
  cbc_health: "https://www.cbc.ca/cmlink/rss-health",
  cbc_sports: "https://www.cbc.ca/cmlink/rss-sports",
  globalnews_politics: "https://globalnews.ca/politics/feed/",
  globalnews_money: "https://globalnews.ca/money/feed/",
  nzherald: "https://www.nzherald.co.nz/arc/outboundfeeds/rss/curated/78/?outputType=xml",

  // ===================== MORE BUSINESS =====================
  quartz: "https://qz.com/rss",
  theeconomist: "https://www.economist.com/rss",
  wharton_blog: "https://knowledge.wharton.upenn.edu/feed/",
  mckinsey: "https://www.mckinsey.com/insights/rss",
  bain: "https://www.bain.com/insights/feed/",

  // ===================== MORE TECH =====================
  venturebeat: "https://venturebeat.com/feed/",
  tnw_latest: "https://thenextweb.com/latest/feed/",
  bgr: "https://bgr.com/feed/",
  geekwire: "https://www.geekwire.com/feed/",
  torrentfreak: "https://torrentfreak.com/feed/",
  boingboing: "https://boingboing.net/feed/",
  hackday: "https://hackaday.com/feed/",
  spectrum_ieee: "https://spectrum.ieee.org/feeds/feed.rss",
  ifixit: "https://www.ifixit.com/blog/feed",
  omgubuntu: "https://www.omgubuntu.co.uk/feed",
  fossforce: "https://fossforce.com/feed/",
  itsfoss: "https://itsfoss.com/rss/",
  linuxjournal: "https://www.linuxjournal.com/node/feed",
  phoronix: "https://www.phoronix.com/rss.php",
  liliputing: "https://liliputing.com/feed/",

  // ===================== MORE GAMING =====================
  gameinformer: "https://www.gameinformer.com/rss",
  hardcore_gamer: "https://hardcoregamer.com/feed/",
  escapist: "https://www.escapistmagazine.com/feed/",
  mp1st: "https://mp1st.com/feed",
  playstationblog: "https://blog.playstation.com/feed/",
  xbox_news: "https://news.xbox.com/en-us/feed/",
  nindies: "https://www.nintendoeverything.com/feed/",

  // ===================== MORE SPORTS =====================
  si_soccer: "https://www.si.com/rss/si_soccer.rss",
  talksport: "https://talksport.com/feed/",
  sportbible: "https://www.sportbible.com/feed",
  olympic_news: "https://www.olympics.com/en/news/rss",
  ufc: "https://www.ufc.com/rss/news",
  pga: "https://www.pgatour.com/rss/news",
  nba_news: "https://www.nba.com/feed/news.rss",
  mlb_news: "https://www.mlb.com/feeds/news/rss.xml",
  nhl: "https://www.nhl.com/rss/news.xml",

  // ===================== MORE MUSIC =====================
  clash_music: "https://www.clashmusic.com/feed/",
  paste_music: "https://www.pastemagazine.com/rss/music",
  diymagazine: "https://diymag.com/rss",
  tinymixtapes: "https://www.tinymixtapes.com/feed",
  fact_mag: "https://www.factmag.com/feed/",

  // ===================== MORE ENTERTAINMENT =====================
  tvline: "https://tvline.com/feed/",
  tvinsider: "https://www.tvinsider.com/feed/",
  paste_tv: "https://www.pastemagazine.com/rss/tv",
  whatsonnetflix: "https://www.whats-on-netflix.com/feed/",
  decider: "https://decider.com/feed/",
  gamesradar_movies: "https://www.gamesradar.com/movies/rss/",
  empireonline: "https://www.empireonline.com/feed/",
  joblo: "https://www.joblo.com/feed/",

  // ===================== MORE SCIENCE =====================
  cosmosmagazine: "https://cosmosmagazine.com/feed/",
  atlasobscura: "https://www.atlasobscura.com/feeds/latest",
  discovermagazine: "https://www.discovermagazine.com/rss/all",
  technologynetworks: "https://www.technologynetworks.com/rss/all",
  futurism: "https://futurism.com/feed",
  singularityhub: "https://singularityhub.com/feed/",

  // ===================== MORE AI =====================
  theaijournal: "https://aijournal.com/feed/",
  synced_ai: "https://syncedreview.com/feed/",
  thegradient: "https://thegradient.pub/rss/",
  importai: "https://importai.substack.com/feed",
  paperswithcode: "https://paperswithcode.com/rss",

  // ===================== MORE INDIA =====================
  mint_opinion: "https://www.livemint.com/rss/opinion",
  outlook_india: "https://www.outlookindia.com/rss",
  rediff: "https://www.rediff.com/rss/inrss.xml",
  wion: "https://www.wionews.com/feeds/india/rss.xml",
  wion_world: "https://www.wionews.com/feeds/world/rss.xml",
  wion_tech: "https://www.wionews.com/feeds/science-technology/rss.xml",
  wion_entertainment: "https://www.wionews.com/feeds/entertainment/rss.xml",
  ndtv_business: "https://feeds.feedburner.com/ndtvprofit-latest",
  ndtv_entertainment: "https://feeds.feedburner.com/ndtvmovies-latest",
  zeenews: "https://zeenews.india.com/rss/india-national-news.xml",
  zeenews_world: "https://zeenews.india.com/rss/world-news.xml",
  abplive: "https://news.abplive.com/feed",
  aajtak: "https://aajtak.intoday.in/rss/default.xml",

  // ===================== MORE CRYPTO =====================
  u_today: "https://u.today/rss",
  coingecko_buzz: "https://www.coingecko.com/buzz/feed",
  bitcoinist: "https://bitcoinist.com/feed/",
  zycrypto: "https://zycrypto.com/feed/",
  cryptobriefing: "https://cryptobriefing.com/feed/",

  // ===================== MORE EUROPE =====================
  kyivindependent: "https://kyivindependent.com/feed/",
  bne_intellinews: "https://www.intellinews.com/rss/",
  thenordics: "https://www.thenordics.com/feed/",

  // ===================== MORE AFRICA =====================
  theafricareport: "https://www.theafricareport.com/feed/",
  iol_za: "https://www.iol.co.za/cmlink/1.640",
  businesslive_za: "https://www.businesslive.co.za/rss/",

  // ===================== MORE HEALTH =====================
  fiercehealthcare: "https://www.fiercehealthcare.com/rss/xml",
  healthaffairs: "https://www.healthaffairs.org/action/showFeed?type=etoc&feed=rss&jc=hlthaff",

  // ===================== MORE EDUCATION =====================
  wired_education: "https://www.wired.com/feed/category/education/latest/rss",
  khanacademy_blog: "https://blog.khanacademy.org/feed/",

  // ===================== MORE ENVIRONMENT =====================
  desmog: "https://www.desmog.com/feed/",
  earthorg: "https://earth.org/feed/",
  ensia: "https://ensia.com/feed/",

  // ===================== MORE LIFESTYLE =====================
  bustle: "https://www.bustle.com/rss",
  thecut: "https://www.thecut.com/feed/rss",
  manofmany: "https://manofmany.com/feed",
  coolhunting: "https://coolhunting.com/feed/",
  uncrate: "https://uncrate.com/feed/",
  gearpatrol: "https://www.gearpatrol.com/feed/",
  thrillist: "https://www.thrillist.com/rss/index.xml",

  // ===================== PODCASTING / MEDIA =====================
  nieman_lab: "https://www.niemanlab.org/feed/",
  poynter: "https://www.poynter.org/feed/",
  cjr: "https://www.cjr.org/feed",
  mediaite: "https://www.mediaite.com/feed/",

  // ===================== MORE MISCELLANEOUS =====================
  nautil_us: "https://nautil.us/feed/",
  longreads: "https://longreads.com/feed/",
  theringer: "https://www.theringer.com/rss/index.xml",

  // ===================== EXPAND: WORLD NEWS =====================
  dawn_world: "https://www.dawn.com/feeds/world",
  dawn_tech: "https://www.dawn.com/feeds/tech",
  tribune_pk: "https://tribune.com.pk/feed/home",
  tribune_pk_tech: "https://tribune.com.pk/feed/technology",
  tribune_pk_sports: "https://tribune.com.pk/feed/sports",
  geo_tv: "https://www.geo.tv/rss/1/0",
  samaa: "https://www.samaaenglish.tv/feed/",
  bbc_us: "http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml",
  bbc_entertainment: "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
  bbc_health: "http://feeds.bbci.co.uk/news/health/rss.xml",
  bbc_magazine: "http://feeds.bbci.co.uk/news/magazine/rss.xml",
  cnn_money: "http://rss.cnn.com/rss/money_news_international.rss",
  cnn_style: "http://rss.cnn.com/rss/cnn_style.rss",
  guardian_sport: "https://www.theguardian.com/sport/rss",
  guardian_travel: "https://www.theguardian.com/travel/rss",
  guardian_food: "https://www.theguardian.com/food/rss",
  guardian_fashion: "https://www.theguardian.com/fashion/rss",
  guardian_art: "https://www.theguardian.com/artanddesign/rss",
  nytimes_magazine: "https://rss.nytimes.com/services/xml/rss/nyt/Magazine.xml",
  nytimes_theater: "https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml",
  nytimes_automobiles: "https://rss.nytimes.com/services/xml/rss/nyt/Automobiles.xml",
  nytimes_obituaries: "https://rss.nytimes.com/services/xml/rss/nyt/Obituaries.xml",
  nytimes_sunday: "https://rss.nytimes.com/services/xml/rss/nyt/SundayReview.xml",
  npr_music: "https://feeds.npr.org/1039/rss.xml",
  npr_culture: "https://feeds.npr.org/1008/rss.xml",
  npr_race: "https://feeds.npr.org/1015/rss.xml",
  npr_food: "https://feeds.npr.org/1053/rss.xml",
  skynews_entertainment: "https://feeds.skynews.com/feeds/rss/entertainment.xml",
  skynews_politics: "https://feeds.skynews.com/feeds/rss/politics.xml",
  skynews_science: "https://feeds.skynews.com/feeds/rss/science.xml",
  dw_culture: "https://rss.dw.com/rdf/rss-en-cul",
  dw_sports: "https://rss.dw.com/rdf/rss-en-sports",

  // ===================== EXPAND: INDIA =====================
  toi_education: "https://timesofindia.indiatimes.com/rssfeeds/913168846.cms",
  hindustantimes_business: "https://www.hindustantimes.com/feeds/rss/business/rssfeed.xml",
  hindustantimes_lifestyle: "https://www.hindustantimes.com/feeds/rss/lifestyle/rssfeed.xml",
  hindustantimes_education: "https://www.hindustantimes.com/feeds/rss/education/rssfeed.xml",
  thehindu_business: "https://www.thehindu.com/business/feeder/default.rss",
  thehindu_education: "https://www.thehindu.com/education/feeder/default.rss",
  thehindu_opinion: "https://www.thehindu.com/opinion/feeder/default.rss",
  indianexpress_business: "https://indianexpress.com/section/business/feed/",
  indianexpress_education: "https://indianexpress.com/section/education/feed/",
  indianexpress_opinion: "https://indianexpress.com/section/opinion/feed/",
  ndtv_food: "https://feeds.feedburner.com/ndtvfood-latest",
  ndtv_auto: "https://feeds.feedburner.com/ndtvauto-latest",
  news18_business: "https://www.news18.com/commonfeeds/v1/eng/rss/business.xml",
  news18_lifestyle: "https://www.news18.com/commonfeeds/v1/eng/rss/lifestyle.xml",
  news18_education: "https://www.news18.com/commonfeeds/v1/eng/rss/education.xml",
  zeenews_tech: "https://zeenews.india.com/rss/technology-news.xml",
  zeenews_sports: "https://zeenews.india.com/rss/sports-news.xml",
  zeenews_entertainment: "https://zeenews.india.com/rss/entertainment-news.xml",
  zeenews_health: "https://zeenews.india.com/rss/health-news.xml",
  wion_sports: "https://www.wionews.com/feeds/sports/rss.xml",
  gadgets360: "https://feeds.feedburner.com/gadgets360-latest",
  carandbike: "https://feeds.feedburner.com/carandbike-latest",
  moneycontrol_personal: "https://www.moneycontrol.com/rss/pf.xml",

  // ===================== EXPAND: ASIA =====================
  cbc_entertainment: "https://www.cbc.ca/cmlink/rss-entertainment",
  cbc_science: "https://www.cbc.ca/cmlink/rss-science",
  abcaus_tech: "https://www.abc.net.au/news/feed/5398694/rss.xml",
  abcaus_science: "https://www.abc.net.au/news/feed/5398692/rss.xml",
  abcaus_business: "https://www.abc.net.au/news/feed/51892/rss.xml",
  abcaus_sports: "https://www.abc.net.au/news/feed/5398710/rss.xml",
  abcaus_entertainment: "https://www.abc.net.au/news/feed/5398716/rss.xml",
  abcaus_health: "https://www.abc.net.au/news/feed/5398706/rss.xml",
  japantimes_business: "https://www.japantimes.co.jp/feed/business/",
  japantimes_sports: "https://www.japantimes.co.jp/feed/sports/",
  japantimes_life: "https://www.japantimes.co.jp/feed/life/",
  globalnews_tech: "https://globalnews.ca/tech/feed/",
  globalnews_health: "https://globalnews.ca/health/feed/",
  globalnews_entertainment: "https://globalnews.ca/entertainment/feed/",
  globalnews_sports: "https://globalnews.ca/sports/feed/",
  dawn_sport: "https://www.dawn.com/feeds/sport",
  dawn_business: "https://www.dawn.com/feeds/business",

  // ===================== EXPAND: MIDDLE EAST =====================
  arabnews_sport: "https://www.arabnews.com/cat/7/rss.xml",
  arabnews_tech: "https://www.arabnews.com/cat/13/rss.xml",
  arabnews_lifestyle: "https://www.arabnews.com/cat/15/rss.xml",

  // ===================== EXPAND: EUROPE =====================
  thelocal_pl: "https://feeds.thelocal.com/rss/pl",
  politico_eu_tech: "https://www.politico.eu/section/technology/feed/",
  euractiv: "https://www.euractiv.com/feed/",
  dw_environment: "https://rss.dw.com/rdf/rss-en-environment",
  euobserver: "https://euobserver.com/rss",
  scotsman: "https://www.scotsman.com/rss",
  walesonline: "https://www.walesonline.co.uk/news/?service=rss",

  // ===================== EXPAND: LATIN AMERICA =====================
  thecitypaperbogota: "https://thecitypaperbogota.com/feed/",
  dialogo_americas: "https://dialogo-americas.com/feed/",
  mexiconewsdaily: "https://mexiconewsdaily.com/feed/",

  // ===================== EXPAND: AFRICA =====================
  mg_za: "https://mg.co.za/feed/",
  vanguard_ng: "https://www.vanguardngr.com/feed/",
  thecable_ng: "https://www.thecable.ng/feed",
  monitor_ug: "https://www.monitor.co.ug/rss.xml",

  // ===================== EXPAND: BUSINESS / FINANCE =====================
  thestreet: "https://www.thestreet.com/feed",
  benzinga: "https://www.benzinga.com/feed",
  kiplinger: "https://www.kiplinger.com/feed/all",
  barrons: "https://www.barrons.com/feed",
  wsjmarkets: "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
  wsj_opinion: "https://feeds.a.dj.com/rss/RSSOpinion.xml",
  wsj_tech: "https://feeds.a.dj.com/rss/RSSWSJD.xml",
  wsj_lifestyle: "https://feeds.a.dj.com/rss/RSSLifestyle.xml",
  wsj_world: "https://feeds.a.dj.com/rss/RSSWorldNews.xml",

  // ===================== EXPAND: TECH =====================
  wired_security: "https://www.wired.com/feed/category/security/latest/rss",
  wired_culture: "https://www.wired.com/feed/category/culture/latest/rss",
  arstechnica_gaming: "https://feeds.arstechnica.com/arstechnica/gaming",
  arstechnica_cars: "https://feeds.arstechnica.com/arstechnica/cars",
  arstechnica_policy: "https://feeds.arstechnica.com/arstechnica/tech-policy",
  nine_to_five_toys: "https://9to5toys.com/feed/",
  techmeme: "https://www.techmeme.com/feed.xml",
  techspot: "https://www.techspot.com/backend/rss/rss.xml",
  neowin: "https://www.neowin.net/feed/",
  betanews: "https://betanews.com/feed/",
  techpowerup: "https://www.techpowerup.com/rss/news",
  talkandroid: "https://www.talkandroid.com/feed/",
  imore: "https://www.imore.com/feed",

  // ===================== EXPAND: PROGRAMMING / DEV =====================
  medium_javascript: "https://medium.com/feed/tag/javascript",
  medium_python: "https://medium.com/feed/tag/python",
  medium_webdev: "https://medium.com/feed/tag/web-development",
  medium_devops: "https://medium.com/feed/tag/devops",
  medium_react: "https://medium.com/feed/tag/react",
  realpython: "https://realpython.com/atom.xml",
  pythonweekly: "https://us2.campaign-archive.com/feed?u=e2e180baf855ac797ef407fc7&id=9e26887fc5",
  theserverside: "https://www.theserverside.com/rss/ContentSyndication.xml",
  codeproject: "https://www.codeproject.com/WebServices/ArticleRSS.aspx?cat=1",
  phparch: "https://www.phparch.com/feed/",
  rubyweekly: "https://rubyweekly.com/rss",
  kotlinblog: "https://blog.jetbrains.com/kotlin/feed/",
  rustblog: "https://blog.rust-lang.org/feed.xml",
  goblog: "https://go.dev/blog/feed.atom",

  // ===================== EXPAND: AI / ML =====================
  nvidia_blog: "https://blogs.nvidia.com/feed/",
  google_ai_blog: "https://blog.google/technology/ai/rss/",
  microsoft_ai: "https://blogs.microsoft.com/ai/feed/",
  meta_ai: "https://ai.meta.com/blog/rss/",
  anthropic_news: "https://www.anthropic.com/rss.xml",
  bengio_yoshua: "https://yoshuabengio.org/feed/",
  distill: "https://distill.pub/rss.xml",
  twomin_papers: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
  aisupremacy: "https://aisupremacy.substack.com/feed",

  // ===================== EXPAND: SCIENCE =====================
  guardian_space: "https://www.theguardian.com/science/space/rss",
  nature_news: "https://www.nature.com/nature.rss",
  science_mag: "https://www.science.org/rss/news_current.xml",
  cell_press: "https://www.cell.com/cell/rss",
  newatlas: "https://newatlas.com/index.rss",
  ars_science2: "https://feeds.arstechnica.com/arstechnica/science",
  theconversation_science: "https://theconversation.com/us/technology/articles.atom",
  labmanager: "https://www.labmanager.com/feed/rss",

  // ===================== EXPAND: HEALTH =====================
  guardian_health: "https://www.theguardian.com/society/health/rss",
  fiercepharma: "https://www.fiercepharma.com/rss/xml",
  healio: "https://www.healio.com/rss",
  sciencedaily_mind: "https://www.sciencedaily.com/rss/mind_brain.xml",
  nih_news: "https://www.nih.gov/news-events/news-releases/feed",
  cdc_news: "https://tools.cdc.gov/api/v2/resources/media/403372.rss",
  healtheuropa: "https://www.healtheuropa.com/feed/",

  // ===================== EXPAND: SPORTS =====================
  guardian_tennis: "https://www.theguardian.com/sport/tennis/rss",
  guardian_rugby: "https://www.theguardian.com/sport/rugby-union/rss",
  guardian_golf: "https://www.theguardian.com/sport/golf/rss",
  guardian_boxing: "https://www.theguardian.com/sport/boxing/rss",
  guardian_f1: "https://www.theguardian.com/sport/formulaone/rss",
  espn_f1: "https://www.espn.com/espn/rss/f1/news",
  espn_golf: "https://www.espn.com/espn/rss/golf/news",
  espn_mma: "https://www.espn.com/espn/rss/mma/news",
  skysports_nfl: "https://www.skysports.com/rss/12040/12691",
  skysports_golf: "https://www.skysports.com/rss/12040/12234",
  skysports_boxing: "https://www.skysports.com/rss/12040/12183",
  cricbuzz: "https://www.cricbuzz.com/cb-rss/cb-top",
  football365: "https://www.football365.com/feed",
  fourfourtwo: "https://www.fourfourtwo.com/feeds/all",
  givemesport: "https://www.givemesport.com/feed/",

  // ===================== EXPAND: ENTERTAINMENT =====================
  guardian_tv: "https://www.theguardian.com/tv-and-radio/rss",
  vulture: "https://www.vulture.com/feed/rss",
  pajiba: "https://www.pajiba.com/feed",
  bloody_disgusting: "https://bloody-disgusting.com/feed/",
  thewrap: "https://www.thewrap.com/feed/",
  movieweb: "https://movieweb.com/feed/",
  wegotthiscovered: "https://wegotthiscovered.com/feed/",
  liveforlivemusic: "https://liveforlivemusic.com/feed/",
  anime_news: "https://www.animenewsnetwork.com/all/rss.xml",
  crunchyroll_news: "https://www.crunchyroll.com/feed",

  // ===================== EXPAND: FOOD =====================
  guardian_food2: "https://www.theguardian.com/food/rss",
  eater_national: "https://www.eater.com/rss/index.xml",
  thekitchn2: "https://www.thekitchn.com/feed",
  cookinglight: "https://www.cookinglight.com/feeds/all",
  delish: "https://www.delish.com/feeds/all",

  // ===================== EXPAND: TRAVEL =====================
  guardian_travel2: "https://www.theguardian.com/travel/rss",
  nytimes_travel2: "https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml",
  fodors: "https://www.fodors.com/feed/",
  tourismreview: "https://www.tourism-review.com/rss.xml",
  breakingtravelnews: "https://www.breakingtravelnews.com/feed/",

  // ===================== EXPAND: AUTOMOTIVE =====================
  motor1: "https://www.motor1.com/rss/news/all/",
  autocar: "https://www.autocar.co.uk/rss",
  autoexpress: "https://www.autoexpress.co.uk/feed/all",
  drivetribe: "https://drivetribe.com/feed",
  motorauthority: "https://www.motorauthority.com/rss/news",
  carthrottle: "https://www.carthrottle.com/feed",

  // ===================== EXPAND: FASHION / BEAUTY =====================
  wwd: "https://wwd.com/feed/",
  fashionista: "https://fashionista.com/.rss/full/",
  manrepeller: "https://repeller.com/feed/",
  beautyindependent: "https://www.beautyindependent.com/feed/",
  byrdie: "https://www.byrdie.com/rss",
  whowhatwear: "https://www.whowhatwear.com/rss",

  // ===================== EXPAND: PERSONAL FINANCE =====================
  wise_bread: "https://www.wisebread.com/feed",
  thebalance_invest: "https://www.thebalancemoney.com/investing/rss",
  daveramsey: "https://www.ramseysolutions.com/rss",
  mrmoneymustache: "https://www.mrmoneymustache.com/feed/",
  financialsamurai: "https://www.financialsamurai.com/feed/",

  // ===================== EXPAND: DESIGN / ARCHITECTURE =====================
  wallpaper: "https://www.wallpaper.com/feed/",
  inhabitat: "https://inhabitat.com/feed/",
  curbed_design: "https://www.curbed.com/rss/index.xml",
  fastcodesign: "https://www.fastcompany.com/co-design/rss",
  colossal: "https://www.thisiscolossal.com/feed/",
  booooooom: "https://www.booooooom.com/feed/",

  // ===================== EXPAND: EDUCATION =====================
  chronicle_he2: "https://www.chronicle.com/section/news/3/feed",
  eschoolnews: "https://www.eschoolnews.com/feed/",
  teachthought: "https://www.teachthought.com/feed/",
  edtechmagazine: "https://edtechmagazine.com/k12/feed",
  schoology_blog: "https://www.powerschool.com/blog/feed/",

  // ===================== EXPAND: ENVIRONMENT =====================
  guardian_animals: "https://www.theguardian.com/world/animals/rss",
  yaleclimateconnections: "https://yaleclimateconnections.org/feed/",
  greenmatters: "https://www.greenmatters.com/rss",
  circularonline: "https://www.circularonline.co.uk/feed/",
  energymonitor: "https://www.energymonitor.ai/feed/",

  // ===================== EXPAND: GAMING =====================
  gamingbolt: "https://gamingbolt.com/feed",
  twinfinite: "https://twinfinite.net/feed/",
  thegamer: "https://www.thegamer.com/feed/",
  gamerant: "https://gamerant.com/feed/",
  segmentnext: "https://segmentnext.com/feed/",
  gamepur: "https://www.gamepur.com/feed/",
  shacknews: "https://www.shacknews.com/feed/rss",

  // ===================== EXPAND: MORE CRYPTO =====================
  coinspeaker: "https://www.coinspeaker.com/feed/",
  cryptonews: "https://cryptonews.com/news/feed/",
  nulltx: "https://nulltx.com/feed/",
  coinjournal: "https://coinjournal.net/feed/",
  crypto_news_flash: "https://www.crypto-news-flash.com/feed/",
  thecryptobasic: "https://thecryptobasic.com/feed/",
  coinpedia: "https://coinpedia.org/feed/",

  // ===================== EXPAND: MORE CYBERSECURITY =====================
  infosecurity_mag: "https://www.infosecurity-magazine.com/rss/news/",
  csoonline: "https://www.csoonline.com/feed/",
  scmagazine: "https://www.scworld.com/feed",
  hackread: "https://www.hackread.com/feed/",
  gbhackers: "https://gbhackers.com/feed/",
  securityboulevard: "https://securityboulevard.com/feed/",

  // ===================== EXPAND: MORE PROGRAMMING =====================
  medium_nodejs: "https://medium.com/feed/tag/nodejs",
  medium_typescript: "https://medium.com/feed/tag/typescript",
  medium_flutter: "https://medium.com/feed/tag/flutter",
  medium_android: "https://medium.com/feed/tag/android",
  medium_ios: "https://medium.com/feed/tag/ios",
  medium_docker: "https://medium.com/feed/tag/docker",
  medium_kubernetes: "https://medium.com/feed/tag/kubernetes",
  medium_aws: "https://medium.com/feed/tag/aws",
  medium_blockchain: "https://medium.com/feed/tag/blockchain",
  medium_datascience: "https://medium.com/feed/tag/data-science",
  flutter_dev: "https://medium.com/flutter/feed",
  docker_blog: "https://www.docker.com/blog/feed/",
  kubernetes_blog: "https://kubernetes.io/feed.xml",
  aws_blog: "https://aws.amazon.com/blogs/aws/feed/",
  azure_blog: "https://azure.microsoft.com/en-us/blog/feed/",
  gcp_blog: "https://cloud.google.com/blog/rss",
  vercel_blog: "https://vercel.com/blog/rss.xml",
  netlify_blog: "https://www.netlify.com/blog/rss.xml",
  nextjs_blog: "https://nextjs.org/feed.xml",
  svelte_blog: "https://svelte.dev/blog/rss",
  vuejs_blog: "https://blog.vuejs.org/feed.rss",
  react_blog: "https://react.dev/rss.xml",
  angular_blog: "https://blog.angular.dev/feed",

  // ===================== EXPAND: MORE SPACE =====================
  esa_news: "https://www.esa.int/rssfeed/Our_Activities/Space_News",
  spacex_updates: "https://www.spacex.com/api/feed",
  arianespace: "https://www.arianespace.com/feed/",

  // ===================== EXPAND: MORE SCIENCE =====================
  sciencenews: "https://www.sciencenews.org/feed",
  theconversation_sci: "https://theconversation.com/us/science/articles.atom",
  researchgate_news: "https://www.researchgate.net/blog/feed/",
  eurekalert: "https://www.eurekalert.org/feed/rss/enn/",

  // ===================== EXPAND: MORE LIFESTYLE =====================
  buzzfeed: "https://www.buzzfeed.com/index.xml",
  upworthy: "https://www.upworthy.com/rss",
  brightly: "https://www.readbrightly.com/feed/",
  popsugar: "https://www.popsugar.com/feed",
  thegoodtrade: "https://www.thegoodtrade.com/feed",
  minimalismlife: "https://www.minimalismlife.com/feed/",
  theeverygirl: "https://theeverygirl.com/feed/",
  cup_of_jo: "https://cupofjo.com/feed/",

  // ===================== EXPAND: MORE DEFENSE =====================
  warzone: "https://www.thedrive.com/the-war-zone/feed",
  armscontrol: "https://www.armscontrol.org/rss",
  navalnews: "https://www.navalnews.com/feed/",
  airforcemag: "https://www.airandspaceforces.com/feed/",

  // ===================== EXPAND: MORE PHILOSOPHY =====================
  plato_stanford: "https://plato.stanford.edu/rss/sep.xml",
  brainpickings2: "https://www.themarginalian.org/feed/",
  psyche_aeon: "https://psyche.co/feed/rss",
  farnam_street: "https://fs.blog/feed/",

  // ===================== 1000+ FINAL PUSH =====================
  ladbible: "https://www.ladbible.com/feed",
  unilad: "https://www.unilad.com/feed",
  digg: "https://digg.com/feed",
  mentalfloss: "https://www.mentalfloss.com/feed",
  howstuffworks: "https://www.howstuffworks.com/feed",
  lifewire: "https://www.lifewire.com/rss",
  investopedia_news: "https://www.investopedia.com/feedbuilder/feed/getfeed?feedName=rss_headline",
  sciencefocus: "https://www.sciencefocus.com/feed",
  pocket_lint: "https://www.pocket-lint.com/feed/",
  trusted_reviews: "https://www.trustedreviews.com/feed",
  t3: "https://www.t3.com/feeds/all",
  stuff_tv: "https://www.stuff.tv/feed",
};

module.exports = SOURCES;
